### ISSUE TITLE
Problem email address (bounce rate) V1.5

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1164]
## Problem email address (bounce rate) V1.5

Provide a more delightful experience and add more clarity for users sending emails. 

As a user, I have emails in my list that don't exist or that I shouldn't send emails to, so I need to focus on problem emails, find them and remove them from my distribution list

Work on relationship between problem email addresses and bounce rate

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] clear up timeframe issue, 24 hours vs 7 days 
- [x] Looking at different patterns for filtering? Maybe after usability testing 
- [x] Guidance earlier in the user journey so they understand problem email addresses when they create an email template 
- [x] Guidance is referenced or linked in other relevant policy documents (TOU, SLA) 
- [x] We know the bounce rate per service in a summary view (such as the live services view in the admin panel) similar to what we currently see for notifications sent in admin panel. (covered by Blazer query for release 1.0)
- [x] revisit timeframes for triggering alarms, as this will set the pattern for suspension and will have consequences
- [x] consider surfacing the times when the bounce rate was at its highest so the Sender knows where to focus
- [x] See all messages sits below texts now, redesign and possibly relabel this so it's more visible and clear that it's global (both email and SMS) etc
- [x] Address tricky echec issue in FR, we need to consider what will seem most natural/smooth to French users so that it does not create a bump that adds to their cognitive load.

##Other
- [x] Generate appropriate log messages so that executions of this feature can be tracked
- [x] Can misuse of this feature cause harm? If yes, create an alert

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

**Comment by yaelberger-commits** [comment]
Could we surface problem email addresses to clients _before_ they send, instead of just after?
How many failures do we have that have happened more than once?
We already know emails on our suppression list, we could potentially surface those

**Comment by yaelberger-commits** [comment]
a glance at a high volume service's review problem email page shows that pattern

**Comment by adriannelee** [comment]
@yaelberger-commits can we move this epic to done?

**Comment by yaelberger-commits** [comment]
We have a few more cleanup tasks to do before this is truly done, but I have moved this epic down the priority list now. We just need to complete the remaining tasks on this EPIC
