### ISSUE TITLE
Address security issue that could misdirect users of Notify 

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#120]
# Task Description

The issue is described in [this security advisory](https://github.com/cds-snc/notification-admin/security/advisories/GHSA-w7wc-rfhq-39j6).

# Task Outcome

More secure Notify!

# Acceptance Criteria

- [ ] The bug is fixed.
- [x] @mohamed-cds sign off on this issue

# QA

- [ ] Test the `set-lang` path with a URL to get redirected to a different workplace. If that does not work, that is good!

# Additional Notes

**Do not put description of the issue in this card.** This is accessible to the public.

**Comment by yaelberger-commits** [comment]
@jimleroyer the link is no longer valid and this card needs refinement so we can prioritize if it needs fixing and how urgently

**Comment by jimleroyer** [comment]
The link still work, I just tried it:
https://github.com/cds-snc/notification-admin/security/advisories/GHSA-w7wc-rfhq-39j6

**Comment by jimleroyer** [comment]
cc @mohamed-cds for advise on this one

**Comment by yaelberger-commits** [comment]
Could be a good task for @andrewleith to introduce him to the codebase and get this done

**Comment by andrewleith** [comment]
The link doesn't work for me either - I think you need certain permissions to see security advisories in a repo!

**Comment by jimleroyer** [comment]
We added @yaelberger-commits this pm as an admin to let her in see this issue. Also added @andrewleith so you can take a look 👀

**Comment by yaelberger-commits** [comment]
Nearly done, Andrew just syncing with Jumana on how to write tests

**Comment by sastels** [comment]
Tested, looks good to me! What do you think @mohamed-cds ?

**Comment by mohamed-cds** [comment]
LGTM as well! Nice job team 🎉
