### ISSUE TITLE
Email Daily Limits Data

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1272]
We introduced Email Daily Limits at the end of July (July 26, 2023) and want to review the data in a couple months to see if the 10,000 default daily limit is the right volume we should keep as a default. 

Questions to answer:

- [ ] What is our daily throughput for emails overall?
- [ ] What is our daily throughput for emails per priority lane?
- [ ] Can we raise our daily email limits past 10,000 by default? Should we? If so, by how much?
- [ ] What is our average total # of emails sent daily through Notify?

- Consider Security
