### ISSUE TITLE
Notify reliably sends messages

### ISSUE THREAD

**Issue by stephenyates-gc** [cds-snc/notification-planning#133]
Our clients need to be able to depend on Notify to send each message. It is imperative that we don’t lose any messages that the system receives. Scaling should not impact message delivery. The API should be available at all times. Security should not compromised.

### Key results

- [x] All messages that get accepted by the API are sent.
- [x] Can support 20K API calls per minute (from 3.5K at start)
- [x] Priority security issues are addressed.

### Constraints

- We need to factor in these constraints:
- Time box to 4 sprints (8 weeks starting September 20)
- Focus on improving the existing functionality, not adding on new functionality.
- Be mindful of the design system, which is expected to be ready in the spring. 
- Set levels/benchmarks of quality that we feel good about, but know that it will not be perfect.

**Comment by adriannelee** [comment]
What are the bottlenecks that we're aware of so far?

- Database (why we're doing batch saving, and always will be a bottleneck)
- SQS (the queue for the database task)
- The pool of longcodes (for sending a lot of messages to meet SLO)
- Data pipeline (discriminate earlier re: different priority of messages in the pipeline - currently, the priorities are not honoured)
