### ISSUE TITLE
Public servants can successfully use Notify

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#134]
Notify needs be inclusive to all public servants who need to send messages.
- Users can work in either language.
- Users can work using assistive technology.
- It is easy for users to understand what to do in Notify regardless of their technical level.

### Key results

- [ ] Get as close as possible to 100% bilingual for client-facing content.
- [ ] We have a process in place to fix untranslated content as we find them.
- [ ] We fix 100% of the critical a11y compliance requirements.
- [x] We have incorporated bilingualism and accessibility into our review process
- [x] We're ready to get an external a11y audit
- [x] Conduct testing to identify critical usability issues.
- [ ] We have resolved 100% of the critical usability issues.

### Constraints

- We need to factor in these constraints:
- Time box to 4 sprints (8 weeks starting September 20)
- Focus on improving the existing functionality, not adding on new functionality.
- Be mindful of the design system, which is expected to be ready in the spring. 
- Set levels/benchmarks of quality that we feel good about, but know that it will not be perfect.

**Comment by yaelberger-commits** [comment]
This is now covered in our more recent Objectives, closing this one
