### ISSUE TITLE
Create warning and critical alarms around the number of daily maximum emails we can send

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#136]
### Task Description

Create warning and critical alarms around the number of daily maximum emails we can send through AWS SES.

### Task Outcome

Have a warning and critical alarms for 60% and 80% threshold respectively, written in Terraform and deployed to both staging and production environments.

### Acceptance Criteria

- [ ] Preconfigured environment variables for both staging and production set with the AWS limit we have.
- [ ] Warning alarm with a 60%  threshold on the 1,000,000 limit we currently have in production.
- [ ] Critical alarm with a 80% threshold on the 1,000,000 limit we currently have in production.

**Comment by yaelberger-commits** [comment]
@jimleroyer can you check if these alarms already exist? Thanks!

**Comment by jimleroyer** [comment]
Confirming we don't have these alarms, I will update the PR description so I remember what it's about next time.

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/136?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels
