### ISSUE TITLE
Batch save: feature flag

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#142]
### Task Description

Put the batch saving behind a feature flag.

### Task Outcome

As a developer,
I want the batch saving behind a feature flag,
So that I can iteratively work on the feature without affecting production logic.

### Acceptance Criteria

- [ ] Feature flag is implemented in the API component.
- [ ] The appropriate environment variable is created and managed in Kubernetes from the manifest repository.
- [ ] The feature flag disables the batch saving by default for both staging and production environments for now.

### Additional Notes

* We can mimic the previous feature flag code that we did for the move of database save from API to celery with these PRs:
  * https://github.com/cds-snc/notification-api/pull/1321/files
  * https://github.com/cds-snc/notification-manifests/pull/569/files
