### ISSUE TITLE
Request a demo page

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1422]
## Description
Make product demo's more self service by letting GC people sign up for them on their own.

Circling back on that; We have just completed the work for Forms, you can see the sign up page here: https://articles.alpha.canada.ca/forms-formulaires/register-for-a-demo/
They put a register for demo link at the bottom of the home page to direct people to it: https://articles.alpha.canada.ca/forms-formulaires/
Notify is up next for the treatment. As we will need to create a new page in Wordpress for Notify like the forms sign up page and modify existing pages to link to it we will need some content capacity from your team. Additionally if you want to update your contact-us page to direct users to the new demo sign up page, you may want to spend some developer capacity to do so. Once the page is created in Wordpress, we on growth can maintain it by updating the links to demos.

WHY are we building?
To allow clients to self-serve a demo request and take some burden off support
WHAT are we building?
A page to sign up for a demo request and the relevant navigation and content
VALUE created by our solution
Self-serve, less support tickets, more demo requests potentially 

## Documentation and Artifacts
Good docs, figma mockups, ADRs, screenshots etc.

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Cypress UI tests if needed.
- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario

## GC Articles Publish checklist
- [ ]  Supporting feature is released and unflagged
- [ ]  Create or update slug
- [ ]  Page content and slug is translated
- [ ]  Document links to and from the page
- [ ]  Add page slug and title to [inventory](https://docs.google.com/document/d/1N6B4fSwoM40m-pDLI70BvLfL7O0n04ndyAXYaIwNbNw/edit)
- [ ]  If new page, add WAF rule
- [ ]  Create new page or update existing page content
- [ ]  Create or update translation to the page
- [ ]  Link translations by choosing an assigned translation
- [ ]  If new page, save as draft
- [ ]  If existing page, update the page
- [ ]  Post page in Slack for last minute reviews
- [ ]  On staging: Clear the cache through GC Notify's admin panel
- [ ]  On staging: Check links, images and language toggle
- [ ]  Give a heads up to the app-team channel once ready to publish
- [ ]  On staging and production: Clear the cache through GC Notify's admin panel
- [ ]  Clear Cloudfront cache in GCA as needed (Andrew and Phil are GCA admins)

**Comment by amazingphilippe** [comment]
Notes from story refinement:
Demo page like forms: 

- Register for a demo as a flow. 
- Growth has a GCA site with demo dates. 
- Remove from contact page, maybe leave a link to demos just in case
- Growth just needs to give us a link. One per month
- New WAF rule for new page
- Some dev work to update contact page
- Edit some pages in GCA maybe?
- Design the demo page
- 

Possible breakdown of work
- [ ] Dev: Remove demo request from contact form
- [ ] Design and Dev: Create demo request page
