### ISSUE TITLE
Support checklist for go live request requirements

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1447]
## Description
Create a checklist for support when a service goes live for various requirements (branding, shared-inboxes, reply-to addresses etc., templates)

WHY are we building?
- Some things are required when going live: no shared inbox members, templates
- Some things are encouraged: Branding, reply-to

WHAT are we building?
VALUE created by our solution

## Documentation and Artifacts
https://docs.google.com/document/d/1-1vkL5ISj0l_TD1z5AkbFKCbvIRolNYiVQqqd9nqiIc/edit#heading=h.p0qgu7za3o4b

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] There is a checklist for the Support team to run through for every go-live request
- [x] Feedback from the Support Team is collected and reconciled 
- [x] Checklist includes steps if a shared inbox is suspected during a Go-Live request 
- [x] Checklist includes canned response for shared inbox found through go-live request
- [x] Checklist includes other scenario for surfacing shared inboxes through regular auditing 
- [x] Checklist includes canned response for shared inbox found through audit

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (Ping Adrianne to add stuff here or find stuff yourself)

## QA Steps
- [ ] Processes are tested in a realistic scenario with a go-live request and any feedback is given to the Notify team or changes are made

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/1447?planning-poker) with Zenhub @mtoutloff @yaelberger-commits @YedidaZalik

**Comment by YedidaZalik** [comment]
Is that this screen<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7c12c33a778a29e100ab0834feddd60e8202c91/Screenshot%202024-01-15%20at%202.30.07%E2%80%AFPM.png" alt="Screenshot 2024-01-15 at 2.30.07 PM.png" />

**Comment by YedidaZalik** [comment]
We began developing the checklist during story refinement:

**Checklist for go live requests**
Check whether the service is using shared inbox. If so, visit the checklist for shared inboxes.
Check that branding follows requirements
Check the logo follows requirements and is sized correctly

**Comment by YedidaZalik** [comment]
Started the checklists in [this document](Started the checklists in this document)

**Comment by yaelberger-commits** [comment]
Reviewed the checklist with the Support Team on Jan. 24, got feedback from them and resolved comments. 
Next step is to incorporate steps for taking action if we find shared inboxes into this checklist document, and doing a side-by-side review of the 2 canned responses (1 for if the Support team finds a shared inbox during a go-live request, the other for if the Notify team finds one during our regular audits) and reconciling any differences in wording or guidance to clients.
Yael is handing this back to @YedidaZalik next

**Comment by YedidaZalik** [comment]
Marie-Sophie provided translation of canned responses https://docs.google.com/document/d/11qTshlUl2On1Uh7Z06maN3u0_kDGzT58hcMmkLDS66k/edit

**Comment by YedidaZalik** [comment]
added to go live checklist https://docs.google.com/document/d/1-1vkL5ISj0l_TD1z5AkbFKCbvIRolNYiVQqqd9nqiIc/edit#heading=h.p0qgu7za3o4b
