### ISSUE TITLE
Research planning 'What is a Service'

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#1475]
We have an idea for this issue and we have some research questions to answer. 

## To-do

- [x] Story refinement to go over the design and draft research questions together with the team
- [x] Draft research plan
- [x] Design changes made for testing
- [x] Make a decision on prototype testing options
- [x] Research plan is reviewed by team
- [x] Recruitment materials are drafted
- [x] Recruitment materials are translated
- [x] Calendly is set up
- [x] Recruitment query is written
- [x] Invitee list is drafted
- [x] Invites are sent out
- [x] Privacy statement is drafted
- [x] Privacy statement is translated
- [x] Facilitation guide is drafted
- [x] Facilitation guide is translated

## Related docs
[Product requirement document](https://docs.google.com/document/d/1TRUx1ncc_uZLKqXkRPZ_R0-IcmwEuN-hpqrzEzM_YGU/edit)
[Figma](https://www.figma.com/file/1ccAvKpMboyDmnUliunnBY/Onboarding-and-set-up-%7C-Embarquement-et-configuration?type=design&node-id=2018-292&mode=design)
[Research plan](https://docs.google.com/document/d/1rKOXlxvhJU-8nZbZaToWyfkKu-LumDz99mzMuR_fLDw/edit#heading=h.e6046ze6x3oz)

**Comment by adriannelee** [comment]
Discussed our questions and changes to make to the design for testing at story refinement today. Posted about next steps on Slack.

Started drafting the research plan and will continue with it & recruitment materials tomorrow.

**Comment by adriannelee** [comment]
Planning is ongoing, waiting for feedback from the team about whether we can do coded prototype. I'll post a few options to consider for timeline and capacity today.

**Comment by adriannelee** [comment]
Decided on testing with a fully coded prototype, considering it'll only take a few days to prepare it. 

Drafted the recruitment email and messaged @mariesophiebezert for a translation
Finished drafting the research plan, shared it with @mtoutloff for a review, especially on the privacy & data section
The research plan is open for feedback from anyone on the team but assigned @yaelberger-commits and @amazingphilippe for their thumbs up.

**Comment by yaelberger-commits** [comment]
I reviewed the research plan today and added some suggestions and comments

**Comment by adriannelee** [comment]
Facilitation guide has been drafted and shared with @amazingphilippe and shared with Marie-Sophie for translation ✅ I let her know it's not urgent since we're not booking these sessions till the last week of January by the earliest

Design changes are complete for testing and the Figma has been shared with MS also for translation.

**Comment by adriannelee** [comment]
Translation for privacy statement and recruitment email came back. I set up the Articles page for the privacy statement links.

**Comment by adriannelee** [comment]
Calendly was set up and invites were sent to 44 clients

**Comment by adriannelee** [comment]
Another batch of 25 invites were sent to see if we can get more francophones to sign up.

**Comment by amazingphilippe** [comment]
Guide d'animation en Français: https://docs.google.com/document/d/1cnjAMNo1IcrKWDU79jZPddwuVkXBYYvSVFJkv9vuNow/edit#heading=h.gjdgxs
