### ISSUE TITLE
Implement queue to buffer notifications

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#148]
### Task Description

Implement the SQS/Redis queue mechanism.

### Task Outcome

Notify needs a buffer space to save all notifications as a batch in the database. After this is done, Notify **will be able** to process multiple notifications coming from the REST API through a celery worker that batch saves into the database. 

**This task does not include the wiring of the queue to any celery worker yet.**

### Acceptance Criteria

- [x] The code is tested with unit-tests under multiple scenarios.
- [x] Redis/SQS receives multiple notifications and store these.
- [x] The queue can provide timed out in flight list (so later we can recover them easily into the inbox).

### Additional Notes

* [ADR to guide the implementation](https://github.com/cds-snc/notification-adr/pull/5/files).

**Comment by yaelberger-commits** [comment]
60-70% done. Minor blocker but know how to resolve it :)

**Comment by yaelberger-commits** [comment]
Partially tested

**Comment by yaelberger-commits** [comment]
90-95% complete
Tested, bugs, edge cases tested. 
Need to bring the branch into a state where the tests are working, something still failing in the pipeline

**Comment by jzbahrai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/148?planning-poker) with ZenHub @iokpala @jimleroyer @sastels
