### ISSUE TITLE
Optimize configuration for batch saving

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning#150]
### Task Description

Optimize configuration for time internal and batch size that works best for both SQS/Redis and AWS Aurora. We have to determine what will be the best time interval and batch number to extract out of the queue to redirect into the batch save.

### Task Outcome

We have an optimization point to reach in terms of stability and fast processing. After this task, we should know the optimal value approximately.

### Acceptance Criteria

- [ ] Show metrics around different configuration values for polling interval period and size of the batch and highlight the best configuration.
- [ ] Test different configurations to find a good, safe value for batch size. Somewhere between 10-500
- [ ] Understand how templates with just 1 variable with dynamic content (big content emails) perform with different batch sizes, when does it break

### QA

- [ ] Realistic usage replicating stress periods in production of thousands of notifications sent through for over 90 minutes pass successfully.

**Comment by jimleroyer** [comment]
We brought the chunk size to a value from 500 to 10 yesterday after an incident in production with a CSV bulk upload through the UI.

**Comment by jimleroyer** [comment]
@sastels  @jzbahrai Do you know if we did any optimization task specifically on batch saving?

**Comment by yaelberger-commits** [comment]
We changed config value during an incident, so now we can move it up or down as needed

**Comment by yaelberger-commits** [comment]
@jimleroyer Should we refine this task and get it ready for the upcoming sprint at the end of March?

**Comment by amazingphilippe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/150?planning-poker) with ZenHub @jzbahrai @sastels @jimleroyer @andrewleith

**Comment by yaelberger-commits** [comment]
We feel good about current optimization, we can always readdress in the future if we have a need to change it.
