### ISSUE TITLE
Clean up feature flag for batch saving

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#152]
### Task Description

We need to clean up code for the feature flag.

### Task Outcome

The batch saving code is in place and no split logic remains between batch vs atomic code.

### Acceptance Criteria

- [x] Feature flag is code from the API project.
- [x] All tests around feature flag has been removed from the API project.
- [x] Feature flag is code from the manifest repository with no remaining environment variable.
- [x] Batch saving is remains as the default logic with no individual saving left for code paths that should solely rely on batch saving.
- [x] [Potentially revert the PR that adds metric around batch saving](https://github.com/cds-snc/notification-api/pull/1495). These would not be necessary anymore if that's the default code path and the SQS metrics would cover it.
- [x] Reconsolidate the existing tests to re-align with the main code path that is now batch saving.

Use this PR as a standard to find what tests need to be moved to new code paths: https://github.com/cds-snc/notification-api/pull/1562 

### Additional Notes

The corresponding task to add the feature flag:

* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/142

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/152?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
@jimleroyer @jzbahrai @sastels Please add your estimates for planning poker

**Comment by adriannelee** [comment]
Jumana will close this one - two work streams came out of this - Steve is working on the other one. Jumana will go through the acceptance checklist
