### ISSUE TITLE
Rate limit requests coming to Notify document download API and API

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#153]
### Task Description

As a security guardian on the Notify application,
I want to prevent too many request to be made against Notify,
So that vulnerability scanners are limited in how much they can hit and discover.

As a Notify support person,
I want to prevent too many request to be made against Notify,
So that users do not bring down the service by their own.

### Task Outcome

Notify will be more secure and stable.

### Acceptance Criteria

- [ ] A rate limit is applied exclusively on calls made to the API.
- [ ] A rate limit is applied exclusively on calls made to the download document API.

### QA
Note that staging has the rate limit set to 5000 requests in 5 minutes
- [ ] send more than 1000 requests / minute to `https://api.staging.notification.cdssandbox.xyz/_status` and verify that after five or six minutes you are counted (or blocked) (check in Athena)
- [ ] add the staging waf_secret to your header and repeat. Verify that you are not counted / blocked this time.
- [ ] repeat with `https://api.document.staging.notification.cdssandbox.xyz/_status`

### Additional Notes

@mohamed-cds knows its [way](url) around Terraform configuration. See this [Slack thread for more info](https://gcdigital.slack.com/archives/CNWA63606/p1635272747012800). 

* The covid alert application [implemented rate](https://github.com/cds-snc/covid-alert-metrics-terraform/blob/main/aws/api_gateway/waf.tf) via `rate_based_statement`.
* The scan-website project [implemented rate and shows how to discriminate](https://github.com/cds-snc/scan-websites/blob/main/terragrunt/aws/api/waf.tf) certain resources via URL paths via `scope_down_statement`.

**Comment by adriannelee** [comment]
Higher priority than the WAF?

**Comment by yaelberger-commits** [comment]
Needs refinement

**Comment by sastels** [comment]
Need:
- [ ] add a secret to the admin -> api request header for the WAF to use to know not to rate limit Notify
- [ ] add the rate limiting WAF rules

**Comment by sastels** [comment]
Added a `waf-secret` to the header for admin -> api calls. It's there in staging, not in production. Must investigate...

**Comment by yaelberger-commits** [comment]
Unblocked by deploy yesterday and investigation was completed

**Comment by YedidaZalik** [comment]
Leaving to run for a couple weeks, has run for around a week, need to check if counted traffic
@jimleroyer ran QA and it's working for more than a week now
