### ISSUE TITLE
Enable TLS with RDS Proxy

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#154]
### Task Description

Enable TLS on RDS Proxy.

### Task Outcome

More secure end-to-end encryption with Notify.

### Acceptance Criteria

- [x] The RDS encryption is enabled at the proxy level on both the staging and production environments.
- [x] The RDS proxy TLS connection is enabled via Terraform.

### Additional Notes

This is required for the ATO of Notify to go through.

### QA Criteria

- [x] TLS connection is enabled for the RDS proxy.
- [x] Smoke tests are performed through the admin and API successfully.

**Comment by yaelberger-commits** [comment]
@jimleroyer was this work ever completed?

**Comment by jimleroyer** [comment]
No, that could be a quick security task with high value.

**Comment by jimleroyer** [comment]
I checked the RDS proxy connection to be TLS yesterday after deployment in staging and it worked.
