### ISSUE TITLE
EPIC: Implement short code for SMS sending

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1561]
In order to make use of our SMS short code we need to introduce the capability to select which SMS vehicle we send messages through. 

- [x] ADR for short code implementation
- [x] Product Requirements Document for short code implementation
- [x] UI changes to introduce use cases radio buttons at template creation flow
- [x] Ability to associate categories of templates with particular SMS sending vehicles

Release Checklist https://docs.google.com/document/d/1W-aMhCx5SfQ8mkAR_g5kJ_POipKEoN5WNgfL9ygElA0/edit

**Comment by amazingphilippe** [comment]
Starting a release checklist process. @yaelberger-commits will attach it here
