### ISSUE TITLE
Run a stress tests with the TEST API Keys

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#159]
### Task Description

To run stress tests against staging environment by exclusively using **TEST API keys**. 

This was reported by a previous performance report and surfaced in our recent ATO process. Apparently, previous version test runs in Notify denoted a performance problem.

### Task Outcome

Confirm if the problem persists and find root cause.

### Acceptance Criteria

- [x] Confirm if problem still exists.
- [x] Create new task that describes the problem and potential solutions.
- [x] Notifications sent using a Test Key should return with a 201

### Additional Notes

This came up as a potential issue during our ATO process. It is described [in the risk register](https://docs.google.com/spreadsheets/d/1GSBptkZe1r1GoTNntGesI31B8eZkTQ4ItTdd172eeOw/edit#gid=0) as such:

> Test keys fake a response from SES to our K8S pods. In doing so the responses come back too fast and cause a pod to crash, this issue can domino to other pods depending on the quantity of the messages sent at once.

**Comment by yaelberger-commits** [comment]
https://cds-snc.freshdesk.com/a/tickets/9501

**Comment by yaelberger-commits** [comment]
Add ourselves to their team, replicate what they do

**Comment by yaelberger-commits** [comment]
Steve can replicate sending to people outside the team using a Test Key, but not using a Team Key

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/159?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @sastels

**Comment by jzbahrai** [comment]
I am going to move this to blocked status. I ran a performance test using the perf-tests in the API repo using a test key. The test key sends to success@amazon. - which isn't listed. I saw no failures on the performance test or 201's. I am unsure if there is anything left to do here.
