### ISSUE TITLE
Drop support for TLS 1.1 and only use 1.2

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#161]
### Task Description

Only enable TLS v1.2 for Notify. This was tried in the past but [a user complained](https://cds-snc.freshdesk.com/a/tickets/7640) that Notify could not be used anymore. This should have been resolved on their end but we need to ask them again before dropping TLS v1.1 support.

### Task Outcome

Notify to be more secure and complete the necessary security ATO tasks.

### Acceptance Criteria

- [x] Ask user if upgrade 1.2 has been upgraded [via this Freshdesk ticket](https://cds-snc.freshdesk.com/a/tickets/7640).
- [ ] Send a notification to known API users about the disabling of TLS v1.1.
- [x] Change appropriate Terraform code to first disable TLS v1.1 support. Leave the code in for now (or have it ready to be merged back in again quickly) for the upcoming scream test.
- [ ] Deploy to production the disabled feature to perform [scream test](http://www.v-wiki.net/the-scream-test/).
- [ ] Wait a week or two.
- [ ] When all is fine and there are no screams, remove TLS v1.1 code support for good.

### Additional Notes

* [Related Terraform code that support TLS v1.1](https://github.com/cds-snc/notification-terraform/blob/9ffc0c1689d583fcb9c060b23c55fee9f909f43e/aws/eks/alb.tf#L68).
* Related PRs that touched the TLS 1.1/1.2 configuration.
  * https://github.com/cds-snc/notification-terraform/pull/246
  * https://github.com/cds-snc/notification-terraform/pull/253
  * https://github.com/cds-snc/notification-terraform/pull/262

**Comment by jimleroyer** [comment]
We got the go from the client, opening PR that will make TLS 2.0 the exclusive secure connection method from now on.
