### ISSUE TITLE
Enforce Annual Limits

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1664]
## Description
As a client, I need to see my limits, so that I can budget the number notifications I send. 

As a Notify support agent, I need to know how to respond to limit increase requests, so that I can be equitable to all services.  

As a Notify product owner, I need to make sure we control our costs, so that the service is sustainable.

WHY are we building?
​​Clients cannot see their annual limits or their current usage status. To calculate their usage, clients have to manually sum up month over month statistics. We also don’t enforce the annual limits, so clients have no incentive to honour them.
WHAT are we building?
*FOCUS ON THIS USER TYPE* Enforce hard annual limit for Self-serve users (25k SMS)
Make annual limits and current usage status visible to users in the UI 
Proactively inform users when their usage nears the annual limit
Help users plan by showing how many messages they have left to send
When user reaches the annual limit, prevent message deployment. 
VALUE created by our solution
Users feel confident about budgeting their message usage.
Users feel that they are given appropriate degree of warning before reaching their annual limit.
Users are not able to send messages after reaching their annual limit.
Existing users are aware of the increase in annual limit

## Documentation and Artifacts
PRD https://docs.google.com/document/d/1qoqzKzt4mXQh1NPtZE_GBqsN0D87wnTbHVNIBRu75D0/edit#heading=h.65ltid8kyr0

## Acceptance Criteria
Given a user is sending higher volumes of notifications from their service, when they are close to or reach their limits, then they've been warned in advance and have been able to plan so they are satisfied with GC Notify.

- [x] Annual limits shown on Messages Sent page
- [x] Annual limits shown on Ready to send page
- [x] Annual limits shown on dashboard
- [x] Annual limits shown in user settings
- [x] Warning email is sent when user reaches 80% of annual limit
- [x] Annual limit updated email is sentwhen annual limit is updated
- [x] Quarterly usage report is sent to all service users
- [x] Annual limits are enforced on the backend (error messages on ready to send + API)
- [x] Budget component created
- [x] Muted variant of remaining messages component is created
- [x] Allow admin to change annual limits in platform admin settings
- [x] Annual limits are tracked per service
- [x] Annual limits on not hardcoded the service settings page

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## Related [Research Airtable](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C?blocks=hide) records
- (find stuff yourself)

## QA Steps
- [ ] Tested in a realistic production scenario
