### ISSUE TITLE
Validate approach to batch saving

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#17]
### Task Description

Validate the approach to implement the batch save of notifications.

### Task Outcome

Validation has been provided with proper review from the team and community.

### Acceptance Criteria

- [x] Working to unblock, input from Antoine.
- [x] ADR is written and proposed.
- [x] Seek out a celery wizard.
- [ ] Design session with CDS community, get input from other devs on our approach.

**Comment by jimleroyer** [comment]
I spoke to Antoine about the approach I'd take. He validated for it and also recommended what he had in mind for doing this task. Approaches are somewhat similar with some differences. I will capture the main option along with the variants in a diagram that I will share.
