### ISSUE TITLE
Upgrade to Flask / Werkzeug 2.0

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#176]
### Task Description

This is a major upgrade for our core Python servers that affect our web services. This is a tech debt we are carrying for a few months as every time we do a dependency bump, it upgrades automatically to version 2 but we need to properly migrate these. These library version 1 also is a security risk at the moment so that would be killing 2 birds with one stone.

### Task Outcome

The upgrade to werkzeug and flask to version 2.0 is done, we eliminated our security risk and technical debt.

### Acceptance Criteria

- [x] Upgrade werkzeug and flask to version 2.0.
- [x] Perform required code migration for werkzeug and flask, as these major version entail major changes in the application.

### QA

- [x] Mob test the Notify application within the group, for the UI and API components. Cover as much its functionality as possible to make sure there are no noticeable differences between the before and after states.

**Comment by yaelberger-commits** [comment]
Pytest, Flask, Werkzeug
GDS did pytest first, it's a lot of work
tried just Admin for Werkzeug 2.0... 
Investigating failed tests (5 or 6)

**Comment by yaelberger-commits** [comment]
Could break this up into multiple cards

**Comment by yaelberger-commits** [comment]
Jimmy and Andrew working on admin test
Jumana and Steve working on API
Admin/Pytest next
Flask/Werkzeug would come after that

**Comment by yaelberger-commits** [comment]
Jimmy to add PR approval for API work

**Comment by yaelberger-commits** [comment]
Upgraded pytest to v 7, but didn't resolve the issue
Might need to sync with other devs
Check the app
GDS has same test and it passes, need to find the difference

**Comment by yaelberger-commits** [comment]
3 PRs in review last week
API
Admin
Utils

Pytest done
2.0.2 Werkzeug goal
2.1.2 in another card

Staging, testing then prod

**Comment by jimleroyer** [comment]
Tagging utils first to label changes with werkzeug upgrade. Then flask 2.0 is next to do.

**Comment by adriannelee** [comment]
Flask upgraded and PR merged - spend some time today going through it together (main code paths) and next is to document the API

**Comment by adriannelee** [comment]
Need to do document download API

**Comment by adriannelee** [comment]
Still looking for a review - THANKS JUMANA

**Comment by jimleroyer** [comment]
Reviewed, looks good and ready to be merged.

**Comment by adriannelee** [comment]
Andrew is still working on document download API, will ask Steve for help today
