### ISSUE TITLE
Increase File descriptor limit from 1024 

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning#183]
### Task Description
This task seeks to increase the retry limit for the docker containers running performancem test.

This has become necessary following observations and errors thrown as seen below:

```
POST,/v2/notifications/email,
"HTTPSConnectionPool(host='api.staging.notification.cdssandbox.xyz', port=443): 
Max retries exceeded with url: /v2/notifications/email 
(Caused by SSLError(OSError(24, 'No file descriptors available')))",1

```

### Task Outcome

Following this proposed increase, the regular occurence of the aforementioned error should reduce.

- [ ] Changing Docker file to upgrade the file descriptor limit and test in staging env.
- [ ] Ticket to AWS written and addressed to get proper guidance on issue.

### Acceptance Criteria

- [ ] Reduction of errors as described above.
- [ ] Investigation is done and we know we cannot fix our perf test issue that way.

**Comment by jimleroyer** [comment]
Link to the AWS support ticket (in staging Notify account):
https://console.aws.amazon.com/support/home#/case/?displayId=9217262601&language=en
