### ISSUE TITLE
[duplicate] Billing

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#217]
**Task Description**
Now that we are signing more Memorandum of Understanding (MOU) with federal departments we need to have features set up for billing

**Following actions to be performed:**

Meetings:
- [ ] Have a meeting to discuss what billing looks like and the touch points that need to happen
- [ ] Inform CDS accounting about MOU and cost recovery (quarterly/ annually)

Structure:
- [ ] Make an invoice structure/ workflow

Tech/ Dev to set up user features:
- [ ] View cost information (e.g. 1 sms message may be split into 3 sms messages because of character limits)
- [ ] Display running cost totals?
- [ ] Information page showing which option they chose (quarterly/ bi-annually) and the date of when it will be billed?
- [ ] Need the ability for services to see how many fragmented SMS they've been sending so they can see total cost

Insights from discussion with Forces who need to send more than 25,000 SMS a year https://docs.google.com/document/d/1ZyvtLPvPNarJLPi6T3hTVmMPgcUwjSph6NHKPzJA2Sk/edit?usp=sharing

**Comment by yaelberger-commits** [comment]
@josh-cds Sharly and I would like to bring this epic into the next sprint starting May 30th

**Comment by yaelberger-commits** [comment]
Out of scope for this year, iceboxed until we have the correct groundwork laid

**Comment by connorscarolyns** [comment]
Closing as duplicate work, new cost recovery epic #2212 should cover everything here.
