### ISSUE TITLE
Privacy + Security work needed to support other govts in future

### ISSUE THREAD

**Issue by sharlychan-cds** [cds-snc/notification-planning#218]
**Task Description**
Need to make Notify ready to serve other governments on the privacy and security side.

**Acceptance Criteria**
Tech/Dev:
- [x] Reduce default retention to 3 days
- [x] Enable redaction
- [ ] Enable alarms for if the service’s data is accessed

Team:
- [ ] Revisit risk register 
- [ ] Conduct a threat modelling exercise in anticipation for all the different government bodies that could use Notify (provinces, territories, municipal, Indigenous governing bodies, crown corporations etc)
- [ ] Update Privacy Impact Assessment to include information learned from above

Additional Notes
