### ISSUE TITLE
Archive the document download frontend component

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#240]
# Description

As a Notify developer, 
I need to shut down the document download API 
So that I get to a simpler architecture of Notify,
And avoid potential security threats of having to maintain an additional unnecessary component.

**It is important to note that we can resurrect this component once we need a front-end for downloading documents. A front-end would be useful to offer file information and potentially a security code asked to the user to protect the documents for example.**

## WHY are we building?

We are destroying here. 💣🤪

## WHAT are we building?

DESTROY&^#@^!!!

## VALUE created by our solution

A simpler architecture for Notify, less resources used and less to maintain.

# Acceptance Criteria** (Definition of done) 

Given a request to download a document, then the request should go straight to the document-document-api instead of its front-end component.

**Goals**

* Security controls in place with simpler architecture and less components.

**Tasks**

- [x] Change the notification-api project to call notification-document-download-api directly instead of notification-document-download-frontend.
- [x] Archive the github repository for notification-document-download-frontend.
- [x] Update documentation.
- [x] Send filesvia prod

**Comment by adriannelee** [comment]
PR is approved, will merge to staging

**Comment by amazingphilippe** [comment]
QA task: Some that has the api running. 
- [ ] Send a message containing an attachment
- [ ] Send a message with a file link

**Comment by amazingphilippe** [comment]
Todays plan

**Comment by jzbahrai** [comment]
Tested both sending a file with an attachment and a link on staging. Received both!

**Comment by sastels** [comment]
A few more PRs to review
https://github.com/cds-snc/notification-pr-bot/pull/27
https://github.com/cds-snc/notification-document-download-api/pull/69
https://github.com/cds-snc/notification-manifests/pull/1200

**Comment by amazingphilippe** [comment]
We don't use the front end on staging! old urls still work and go to the api.

**Comment by jzbahrai** [comment]
reviewed all 3 Prs

**Comment by sastels** [comment]
Left: remove the document download frontend pod from the k8s cluster: merge 
https://github.com/cds-snc/notification-manifests/pull/1200,
check that staging still works, and release.

After that we can archive the repo.

**Comment by sastels** [comment]
removed from staging, looks fine. next step remove from prod.

**Comment by sastels** [comment]
the frontend is no longer used anywhere in Notify and is ready to be archived.
Will first investigate what services (Snyk, others?) that are connected to it.

**Comment by sastels** [comment]
Archived!
