### ISSUE TITLE
Update and publish policy documentation for Notify users 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#270]
_Update and publish policy documentation for Notify users_

# Description

As the Notify team, we need to be able to ensure that users understand the policies and Terms of Use of signing up to use Notify so that we can mitigate security risks associated with users using the service incorrectly or not keeping good security practices and ensure Notify's reputation isn't impacted negatively. 

As a Notify User, I need to know how Notify maintains a secure, privacy preserving, reliable and accessible service so that I can have confidence using it, approving its use, or assessing it for use. 

WHY are we building?
There are security risks and risks to Notify's reputation if users misuse our service, intentionally or unintentionally

WHAT are we building?
A better sign up process that sets expectations with users and provides Notify some protection and risk mitigation if there is misuse. 

VALUE created by our solution
Fewer security incidents because users are better aware of their responsibilities and the proper use of the Notify service

# Acceptance Criteria** (Definition of done) 

- [x] Updated Security Statement is published
- [x] Updated Privacy Statement is published
- [x] New SLA is published
- [x] Updated Terms of Use are published
- [x] Users are able to refer back to the terms of use easily
- [x] Users have access to guides that will help them follow the terms
- [x] Updated Terms of Use must be acknowledged by new users upon account creation
- [x] Current Users are notified of changes to policy documents and updated Terms of Use by email 
- [x] Stakeholders have provided input into new/updated policy documents 
- [x] Security Statement has been tested with users 
- [x] SLO research has been completed 
- [x] Update our Accessibility statement and disclose critical issues we have not yet resolved

Transfer to ESDC checklist
- [x] update Privacy Notice to align with ESDC authorities
- [ ] audit Terms of Use
- [ ] audit Service Level Agreement
- [ ] audit Security Statement 
- [ ] audit Service Level Objectives
- [ ] audit Homepage and public website

Optional
- [x] New SLOs are published 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

[Folder for SLA work ](https://drive.google.com/drive/folders/1R3yoFXiqZ3msMizVbdsbMwRbNTVuueXv)
[SLA Brainstorm document](https://docs.google.com/document/d/1gSrMa_uKKcTsxr31s3Z6BINB6PZr7HRJI70Xb9Qkw60/edit#heading=h.vjdo2z8f75kx)

**Comment by yaelberger-commits** [comment]
Advice from @jimleroyer 
My general guidance before raising the API limit would be:
Users should implement rate limit on their side normally. This is a normal thing to do and should be in our SLA. Does the user really need to send all of these as fast as they can? Our celery workers will slow things down anyway and even if they send as fast in the API, that won't be sent as quick. That means we'll get more alarms too raised that we don't send quick enough.

**Comment by yaelberger-commits** [comment]
SLA v1.5 is completed and sent for translation. Ready to publish once we have the capability with GC Notify. Moving off the high priority list until we have capacity to work on v2.0

**Comment by YedidaZalik** [comment]
Attaching [Airtable for itemizing policy content on the Notify website](https://airtable.com/apph6C5pHjcgb1SE2/tblxywaKnRt22Ep4t/viwBLiclFIbhZyTeO?blocks=hide)

**Comment by YedidaZalik** [comment]
At the appropriate time, in the privacy statement, clarify the difference between the two references to location (bolded)?
We use web analytics
Analytics show how people use our web pages. By studying how people navigate, we can improve GC Notify.
We use Google Analytics for information about:
Pages people visit, links they select and documents they download.
Types of operating systems that visit GC Notify.
Browsers that visit GC Notify and the browser’s approximate **location**.
Date and time of visits.
We do not use analytics to collect information that could identify you or your **location**.
