### ISSUE TITLE
Clean up feature flag for celery notification save

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#29]
# Task Description

Make the database save happening within celery a permanent and static code path. At the moment, this is enabled only when the feature flag is on but it's always on in staging and production after a few months.

Remove the feature flag for `FF_NOTIFICATION_CELERY_PERSISTENCE` where the code that is enabled by this configuration is kept and the previous older code is removed.

# Task Outcome

The notification save that happened outside of a celery task should not happen anymore and default code path should be what the `FF_NOTIFICATION_CELERY_PERSISTENCE` feature flag enables.

Most important, this should increase the test coverage that is currently split in different code path due to the various feature flags we have on critical logic paths.

# Acceptance Criteria

- [x] Code of database notification save within API is removed from the *notification-api* project.
- [x] Code of database notification save within celery is kept from the *notification-api* project.
- [x] The `FF_NOTIFICATION_CELERY_PERSISTENCE` feature flag is removed as an environment variable from the listing in the *notification-manifests* project.
- [x] Reconsolidate the existing tests to re-align with the main code path that is now batch saving.
- [x] Use this PR as a standard to find what tests need to be moved to new code paths: cds-snc/notification-api#1562

# Additional Notes

Related PRs:

* https://github.com/cds-snc/notification-api/pull/1321
* https://github.com/cds-snc/notification-manifests/pull/651

@Moro-Code and @jimleroyer would know where the code is applied and what to remove.

## Impact
Makes our job harder because we have a feature flag there that doesn't need to be
Risk that we might have bugs and the existing tests aren't catching it because feature flags

Some unknowns and complexity

**Comment by sastels** [comment]
API parts of this (first 2 points) done in https://github.com/cds-snc/notification-api/pull/1439

**Comment by jimleroyer** [comment]
Added the tests reconsolidation acceptance criteria and re-estimated from a `2` to a `8`.

**Comment by yaelberger-commits** [comment]
Ready for a conversation about whether to move tests

**Comment by yaelberger-commits** [comment]
Only bring into sprint 25 if we have capacity, otherwise at the top of Product Backlog for next sprint

**Comment by yaelberger-commits** [comment]
Maybe 1/3 or 50% done

**Comment by yaelberger-commits** [comment]
Some tests were not finished refacturing, so going through those now

**Comment by adriannelee** [comment]
PR up yesterday

**Comment by jimleroyer** [comment]
There are two tests left to [re-implement before closing this issue](https://github.com/cds-snc/notification-api/pull/1570/files#r919416342):
* test_should_not_save_email_if_restricted_service_and_invalid_email_address
* test_should_not_save_sms_if_team_key_and_recipient_not_in_team

**Comment by jimleroyer** [comment]
Talked with Jumana, we'll bring this back to the sprint backlog to complete the two missing tests.

**Comment by adriannelee** [comment]
Moving to done, since there isn't much that can be QA'd
