### ISSUE TITLE
Setting up GC Articles as CMS for Notify public website

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#296]
_Setting up GC Articles as CMS for Notify public website_

# Description

As a designer, content designer, PM or lead the Notify Team, I need to be able to update or change the public-facing Notify website so that I can help grow the Notify product without needing developer resources and time to make updates. 

WHY are we building?
- We are copying the content of the public-facing website over to GC Articles so we can make updates easily without needing developer effort and time and add new content pages
- We are using GC Articles as a CMS to experiment with a new product in the Platform product suite
WHAT are we building?
- We are using the GC Articles Platform as a CMS for our static GC Notify website
VALUE created by our solution
- Ability to quickly and easily update the website content and add new pages based on data and user feedback
- Ability to send updates to clients of Notify using GC Articles and GC List
- Ability for GC Articles team to see the product being used in the wild and experiment and test the product
- GC Articles is free for us to use and we have support from the GC Articles team to get started

# Acceptance Criteria** (Definition of done) 

- [x] Documentation (IA) for which pages are pulling content from GC Articles CMS and which are not
- [x] All cards under the epic are completed

- [x] Bilingual URLs

- [X] Look and feel (headers and footers, font, Navigation, Information Architecture)

- [x] QA all pages in staging before publishing in production

- [x] Cache GC articles pages so we don't lose speed, add option in UI to purge cache from Notify admin

**Comment by yaelberger-commits** [comment]
All cards in this epic are completed @amazingphilippe and @andrewleith I am moving it to done
