### ISSUE TITLE
Re-integrate security fix around scheme check on file upload

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#30]
### Task Description

The SRE team provided [a security fix](https://github.com/cds-snc/notification-api/pull/1344) a while ago which triggered a production issue. A code reversal was applied to fix the issue in the short term, but mid-term, there is a fix that was provided following that could work.

We need to review the security issue and make sure we reintegrate it, if deemed necessary (most probably it was!).

### Task Outcome

Increased security. The security fix is re-applied but without the bug.

### Acceptance Criteria

- [ ] [Review initial security fix](https://github.com/cds-snc/notification-api/pull/1344) and understand it
- [ ] [Review secondary fix](https://github.com/cds-snc/notification-api/pull/1356) and understand it
- [ ] Apply more changes to the secondary fix if necessary
- [ ] Explain to the team what the fix did and why we need it
- [ ] Final review & merge and we're hopefully more secure

### Additional Notes

* https://github.com/cds-snc/notification-api/pull/1344
* Mohamed and Omar worked on these so they will be helpful to understand these changes.
