### ISSUE TITLE
Set expectations with a service sending high volume of SMS

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#321]
- [x] good SMS message part batch size
- [x] 1,000 daily message part limit
- [x] ~per minute rate limit as well to prevent bursts of SMS~
- [x] set expectations that Notify is not a good tool for recurring blasts of SMS in a short period

**Comment by yaelberger-commits** [comment]
Prioritize this work in September so we can be ready to validate all usability fixes by end of October.

**Comment by adriannelee** [comment]
Research docs: https://drive.google.com/drive/folders/1hp6JyMGfOb5J4LvraC5VlXTTXuZjjXzt

Blocked: sent the invite to translation - due date is for Sept 14

**Comment by yaelberger-commits** [comment]
@jimleroyer Would we consider this done? 
Do we still need to implement a per minute rate limit to prevent bursts of SMS?

**Comment by jimleroyer** [comment]
@yaelberger-commits I think I am now clueless on what I meant back then with `per minute rate limit as well to prevent bursts of SMS`. I should have added some more details about it. We have an API rate limit at entry, we will buffer the SMS in the system and then send with a rate that is aligned with what AWS expects. I'd say let's remove it as an AC and if it was ever an issue, we'll get to know soon when we do the scale tasks.
