### ISSUE TITLE
Sharing Responsibilities with Senders

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#330]
_Sharing Responsibilities with Senders_

We want to explicitly share responsibilities that we hold and that the user holds so that we can enforce best practices and standards so that notify is reliable for everyone using it.

Notify users need to know what best practices and behaviours are enforced when using Notify to get the best performance, and what behaviours introduce risk for Notify and other users and could result in their service being turned back to Trial mode. 

- Help reduce incident occurrences. 
- Help reduce support ticket volume.
- Help reduce security/privacy/legal risks for Notify.

# Key results

- Users and CDS know about rate limits
- Users and CDS know about API rate limits.
- Users and CDS know about cost recovery and billing, if applicable.
- Users and CDS know about SMS best practices and validating numbers.
- Users and CDS know about throttling large volume.

# Potential tasks

- [x] Content audit of Notify documentation and statements to organize
- [x] GC Notify team updates terms of use
- [x] GC Notify team updates Service Level Agreement 
- [x] GC Notify team updates privacy statement
- [x] GC Notify team updates security statement
- [X] GC Notify team updates knowledge base in Freshdesk with FAQs, SMS email
~~- [ ] GC Notify team and TBS Finance finalize MOU process~~
- [x] TBS legislative authority to work with P/T, municipalities
