### ISSUE TITLE
Add GTM code snippet to website source code

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/notification-planning#362]
# Description

There's a Google Tag Manager (GTM) code snippet to add to the Notify website source code, so that GTM can send data to Google Analytics.

# Task

Please find the code snippet in this [document](https://docs.google.com/document/d/1bbJ6wRLexrOoV_Hw1JmnXb0CmiePdTqnH9qDAlPAX6E/edit?usp=sharing).

# Acceptance Criteria

- [x] Google Tag Manager is activated on the Notify web application, i.e. it can be configured with tags in GTM and react properly with previously defined identifiers as indicated [in this document](https://docs.google.com/document/d/1eB8efXRfJUhQWKrGK7YC0khaTloofGzmjfj3liR5Iwk/edit?pli=1#heading=h.jj00kvfr2rcm).

# QA Testing

- [x] Test existing configured tags in GTM with the staging environment (make sure fix is deployed in the environment before test).
* Create a new tag testing an element identified as indicated [in this document](https://docs.google.com/document/d/1eB8efXRfJUhQWKrGK7YC0khaTloofGzmjfj3liR5Iwk/edit?pli=1#heading=h.jj00kvfr2rcm) targeting staging environment.
- [x] Test existing configured tags in GTM with the production environment (make sure fix is deployed in the environment before test).
* Create a new tag testing an element identified as indicated [in this document](https://docs.google.com/document/d/1eB8efXRfJUhQWKrGK7YC0khaTloofGzmjfj3liR5Iwk/edit?pli=1#heading=h.jj00kvfr2rcm) targeting staging environment.* Create a new tag testing an element identified as indicated [in this document](https://docs.google.com/document/d/1eB8efXRfJUhQWKrGK7YC0khaTloofGzmjfj3liR5Iwk/edit?pli=1#heading=h.jj00kvfr2rcm) targeting production environment.

**Comment by jimleroyer** [comment]
Note that the code snippet is almost the same as what we already have over there:
https://github.com/cds-snc/notification-admin/blob/4050be352e939438e21f9da11aeaa1040c019e49/app/templates/partials/analytics.html#L4

We could replicate what we have and register Google tag manager with the new code `GTM-KRKRZQV`.

**Comment by sastels** [comment]
Do we just need to replace the id in 
https://github.com/cds-snc/notification-admin/blob/4050be352e939438e21f9da11aeaa1040c019e49/app/templates/partials/analytics.html
with the new tag?

**Comment by jimleroyer** [comment]
@sastels It's apparently a different tag. I think we can reuse the same code, but we might have to investigate a bit to see if we replace or add, and if we can reuse the same piece of logic (I think we use something similar worst case scenario as the shared code snippet from Elise document will basically document almost the same).

**Comment by sastels** [comment]
:thinking: Looking at this
https://developers.google.com/analytics/devguides/collection/gtagjs
possibly we just need a new `gtag('config', ...);` line.

**Comment by EliseKa** [comment]
For what it's worth, I had a chat with Omar, he confirmed that for the CDS website, they keep both the Google Analytic tracking code and the Google Tag Manager code snippet. 

`src="https://www.googletagmanager.com/gtag/js?id=UA-102484926-14` is the Google Analytics tracking code.

**Comment by sastels** [comment]
Yeah, looking at https://support.google.com/tagmanager/answer/7582054?hl=en, Google Tag Manager and gtag.js seem to be different things.

**Comment by yaelberger-commits** [comment]
Let's discuss with Elise whether the tags work or not, and what the next steps will be

**Comment by EliseKa** [comment]
Yesterday I tried connecting Google tag manager to the heroku url Steve had created, and it didn't work. I believe some investigation will be needed by a developer.

In the meantime, I found out I could try doing some configuration by temporarily injecting the GTM container into any website (happens within the boundaries of my browser) with the help of [Data Layer Inspector](https://chrome.google.com/webstore/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom?hl=fr) plugin.

**Comment by yaelberger-commits** [comment]
@EliseKa can you please let us know the difference between this card and this one: https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/90 
If they are duplicates, we can close this one.

**Comment by EliseKa** [comment]
@yaelberger-commits The current card is just for Google Tag Manager. I need help from the devs to make the tagging work and send data about events such as clicks to Google Tag Manager and then Google Analytics.

The second card you linked is for Google Analytics. To make the traffic recorded by Google Analytics representative of real public use, we need to filter out internal traffic from us (it won't be perfect, but we'll at least filter out everyone who's an Admin). And we also need bilingual urls so we can more easily differentiate traffic on EN and FR pages.

**Comment by EliseKa** [comment]
@iokpala is currently helping me out with this task

**Comment by jimleroyer** [comment]
I updated the IDs on the GTM event tracking document. My next task would be to make the Google Analytics and Google Tag Manager a bit more secure by customizing the installation (it seems we were always at risk since we forked Notify). This should be relatively quick (1-2 hours) and then I will jump on testing the IDs on the Wordpress installation.

**Comment by jimleroyer** [comment]
Reviewing the scope of this task, I realize that this could be considered complete after I bring the security update to the GTM+GA scripts installation. We went even a bit further by testing if GTM does work and configuring a base setup for testing purposes, to be completed.

I just wonder if we should close this task and create a new one and if I we are going over the scope of this sprint. I am good with helping a bit more Élise as she will definitely need some more dev help to make GTM work and we're currently in a momentum. 

@yaelberger-commits What do you think?

**Comment by yaelberger-commits** [comment]
@jimleroyer I agree if you've completed this task, but there is more work to do on GTM to move this task to Done when ready, and create a new task for the next steps to fully implement GTM. You can put it in New Issues, but if you think there is capacity to keep going with it this sprint, just let me know in Slack and Josh and I will discuss bringing it in to the remainder of this sprint.

**Comment by EliseKa** [comment]
I think we can close this card, I had already another card exactly for testing purposes once the tracking code works. https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/328

**Comment by yaelberger-commits** [comment]
Jimmy in testing phase

**Comment by jimleroyer** [comment]
Moved this to QA. This was just merged into the staging environment. I will add some testing steps into the card to check against staging if GTM works.

**Comment by jimleroyer** [comment]
I removed myself from the task, letting someone else test this for the QA process.

**Comment by yaelberger-commits** [comment]
Can be picked up by Élise or Yael for QA as she didn't work on the implementation.

**Comment by EliseKa** [comment]
QA testing completed

- All tags work on staging, and I created a new tag targeting staging that works.
- All tags work on prod, and I created a new tag targeting prod that works.

I published the new changes and created a version in GTM called "QA testing".
