### ISSUE TITLE
Migrate other Notify pages to GC Articles

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/notification-planning#373]
# Task

The following pages must be added in GC Articles:

- [x] https://notification.canada.ca/activity -- DELETED
- [x] https://notification.canada.ca/privacy
- [x] https://notification.canada.ca/security
- [x] https://notification.canada.ca/a11y
- [x] https://notification.canada.ca/terms
- [x] https://notification.canada.ca/guidance
- [x] https://notification.canada.ca/contact -- DELETED
- [x] https://notification.canada.ca/register -- DELETED
- [x] https://notification.canada.ca/sign-in -- DELETED
- [x] https://notification.canada.ca/forgot-password -- DELETED

While doing so, document the things you can't reproduce.

**Comment by EliseKa** [comment]
**Privacy**

- Able to reproduce the bullet points by copying a list block with the CSS class Phil added
- Spacing between paragraphs still to fix (too large)


**Security**

- Can't reproduce the nested bullet points

**Comment by amazingphilippe** [comment]
The form pages can remain in our code. They have less content and benefit less from being integrated with GC Articles.

**Comment by EliseKa** [comment]
@amazingphilippe Aaah gotcha. Making a note that we should be careful about their urls, they're still part of the unauthenticated pages of the website

**Comment by amazingphilippe** [comment]
Reviewing these pages in #393
