### ISSUE TITLE
Make the API lambda production ready

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#38]
### Task Description

There are remaining tasks to make the Lambda API production ready. Let's use this card as an umbrella for all of these.

### Task Outcome

API Lambda will run in production and we can make releases using these.

### Acceptance Criteria

- [x] We can make targeted releases to production using the release SHA IDs.
- [x] The Terraform production configuration files have proper values.
- [x] The Terraform production description files are properly defined.

### Additional Notes

There were some comments in general around missing pieces [in this PR](https://github.com/cds-snc/notification-terraform/pull/289/files).

**Comment by yaelberger-commits** [comment]
Waiting for canary test to run before considering done
