### ISSUE TITLE
api lambda: Use Canary release to slowly rollout

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#39]
### Task Description

Implement a Canary release to rollout the API Lambdas. We could split incoming API traffic into the Kubernetes machines and the API lambdas, starting at a slow number for the latter. Hence, we would minimize potential issues that could surface when we redirect traffic to the lambdas and always have a revert mechanism in place in case that it goes the situation is out of control.

### Task Outcome

So we can easily rollout the usage of API lambdas without hiccups. 

### Acceptance Criteria

- [ ] Have a canary release in place for the staging environment to test the mechanism in itself.
- [ ] Have a canary release in place for the production environment. 
- [ ] We can have 0% of traffic redirection to either the API lambdas or the Kubernetes machines.
- [ ] We can change the traffic knob easily and quickly between the kubernetes machines and the API lambdas.

**Comment by jimleroyer** [comment]
This card as described was more of the epic of canary release task. I am tempted to close this one as we broke down the tasks in individual cards for a canary release.
