### ISSUE TITLE
Prepare for the Hackathon

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#4]
Prepare for the team to work together to take a chunk out of the accessibility issues in Notify.

## Objectives:
1. Make sure all of us are capable of finding, tracking and fixing a11y issues in Notify
2. Make sure we are able to correctly prioritize and identify the severity of the a11y issue we find. 

## Why we need 2 objectives? 
It's one thing to fix a bunch of a11y issues, it's another to be able to find them. We won't be fixing issues if we can't find them on our own.

## Done when
- We have a decent amount of a11y issues ready to be fixed. **Coverage TBD**.
- We have validated our manual testing plan using training and outside expertise. 
- We have a solid manual testing plan that can be shared with the team.
- We have scheduled the hackathon
- The team is prepared for the hackathon. (Right mind space, right tools set up, ready to tackle a11y issues)

## Out of scope
- Automated testing ready before the hackathon
- 100% coverage of a11y issues. We'll only make sure to have enough work to tackle
- Fixing all issues. We'll do as much as possible, and keep working on fixing after the hackathon. This is a learning opportunity and a starting line, not a finish line.

## Dependencies
- No emergencies happen. We need to be able to focus
- We have enough issues to fix for a two day duration

**Comment by amazingphilippe** [comment]
## Todo
- [ ] Validate our approach against the training
- [ ] Complete the manual assessment as much as possible
- [ ] Schedule the hackathon
- [ ] Prepare for the hackathon with a clear plan so the team can hit the ground running.
- [ ] Prepare intro deck

**Comment by amazingphilippe** [comment]
Planning document: https://docs.google.com/document/d/13AU4a6IXC2QqU0aYZBaC2O_egB9Iq2bTdQwdOeJRV_s/edit#
