### ISSUE TITLE
Make production Python configuration more reliable

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#421]
# Description

As a Python developer,
I want the application deployment to fail,
When there is a misconfiguration,
So that I can properly detect a misconfigured feature instead of going through the deployment normally.

## WHY are we building?

To deploy more reliable software and get alerted early on when there is an unexpected configuration value that can be misinterpreted in a way contrary to our intentions.

## WHAT are we building?

Safer values in our configuration files. If a value is not recognized, fail the software early on to avoid unintended consequences.

## VALUE created by our solution

More reliable software and less mistakes.

# Acceptance Criteria** (Definition of done) 

- [x] Applied in ADMIN, API ~~and DOCUMENT-DOWNLOAD-API~~ (moved to separate card) components.
- [x] The boolean values in the Python configuration files need to be configured with explicit `true` or `false` values instead of different various strings that can be interpreted vaguely, e.g. presence of a string versus absence of a string.
- [x] Proper unit tests written against the newest evaluation logic.
- [x] New configuration restrictions applied in `.env` files, Terraform files that store environmental values and any related environmental values throughout the stack consuming the API and ADMIN components.
- [x] document changes in a short ADR

**Comment by yaelberger-commits** [comment]
I've reviewed, thanks all good!

**Comment by patheard** [comment]
Brainstorming has been added in #424.

**Comment by yaelberger-commits** [comment]
Switching to environs library

**Comment by patheard** [comment]
Staging API just had the `environs` change applied and all changes are expected (related to the new pod deploying on a new cluster worker node and a new Fido2Server object reference):
```diff
$ diff staging-config-pre.json staging-config-post.json 

<     "CLOUDWATCH_AGENT_ENDPOINT": "tcp://ip-10-0-2-119.ca-central-1.compute.internal:25888",
---
>     "CLOUDWATCH_AGENT_ENDPOINT": "tcp://ip-10-0-2-245.ca-central-1.compute.internal:25888",
232c232
<     "FIDO2_SERVER":<fido2.server.Fido2Server object at 0x7f1519d1eb80>,
---
>     "FIDO2_SERVER":<fido2.server.Fido2Server object at 0x7fc6e9e441c0>,
299c299
<     "STATSD_HOST": "ip-10-0-2-119.ca-central-1.compute.internal",
---
>     "STATSD_HOST": "ip-10-0-2-245.ca-central-1.compute.internal",
```

**Comment by patheard** [comment]
With this change deployed to prod, we can now see there's a configuration mismatch between the Lambda API and k8s API pods.  This will be the next task to investigate.

**Comment by yaelberger-commits** [comment]
Working through trying to keep two environments in sync

**Comment by mohamed-cds** [comment]
Dependent on https://github.com/cds-snc/notification-planning/issues/458

**Comment by yaelberger-commits** [comment]
PR open for review

**Comment by patheard** [comment]
# Todo
- [ ] Document the current config sync with Lambda API in an ADR.

**Comment by patheard** [comment]
Now that we're adding config logging to other services, @jimleroyer had a good suggestion to move repeated code out into the `notification-utils` project so it can be shared and keep everything nice and DRY.

**Comment by yaelberger-commits** [comment]
Prod release we need to do
Need config logging into notify-admin

**Comment by yaelberger-commits** [comment]
Closing this one, creating some new subtasks to continue work

**Comment by patheard** [comment]
Validated that non-sensitive config for Lambda API and k8s API is now in-sync in both Staging/Prod.
