### ISSUE TITLE
Gradually ramp up the lambda API in production

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#438]
# Task

Gradually ramp up the lambda API at different scheduled threshold in production.

# Timeline

If everything is fine with previous steps. We can reevaluate if we discover issues, lack resources, etc...

* Bump at 10% on March, 7th
* Bump at 25% on April, 4th
* Bump at 50% on April, 11th
* Bump at 100% on April, 18th

# Acceptance criteria

- [x] Monitor the deployed lambda API in production especially 2pm when HC send their API batch.
- [x] Have a roll back strategy ready in case things go on 🔥.
- [x] Bump at 10%
- [x] Bump at 25%
- [x] Bump at 50%
- [x] Bump at 100%

# QA

- [ ] Smoke tests passing.
- [ ] Admin dashboard working as expected.

# Notes

* Make the changes early in the morning, allowing developers to quickly address issues if any is raised during the day.

**Comment by yaelberger-commits** [comment]
Moved into Product Backlog

**Comment by yaelberger-commits** [comment]
@mohamed-cds to bump on March 14 to 25% and then look for errors

**Comment by patheard** [comment]
This should be put on hold until the config differences between Kubernetes and the Lambda function are sorted out (tracked in #458).

**Comment by yaelberger-commits** [comment]
Update dates in the description to reflect

**Comment by patheard** [comment]
I've adjusted the 25%, 50% and 100% dates to reflect the new timeline caused by the config sync fixes.

**Comment by patheard** [comment]
The Lambda API has been scaled back down to 0% as we investigate the New Relic incident around a high percentage of `No row was found for one()` errors.

Initial investigation is being done by adding more logging:
* cds-snc/notification-planning#537

**Comment by patheard** [comment]
Lambda API has been bumped back up to 25% and continuing to monitor.  Errors seemed to be mostly related to prod smoke test polling behaviour, but because of the lower Lambda API traffic percentage, these triggered a New Relic incident.

**Comment by patheard** [comment]
Lambda API is now serving all requests in prod.
