### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by stephenyates-gc** [cds-snc/notification-planning#5]
As part of outcome 2, we will address accessibility issues with Notify.

Key results
- [x] We fix 100% of the critical compliance requirements.
- [x] We have incorporated bilingualism and accessibility into our review process
- [x] We're ready to get an external a11y audit
