### ISSUE TITLE
Forced reset password feature

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#520]
# Description

As a Notify admin, 
I need to trigger password reset for one or many users,
so that I can increase security when situation demands it.

As a Sender,
I need to understand why my password was invalidated and what my next steps are to regain access to my account
So that I can log into Notify.

## Details

We need a way to trigger a password reset on users, making previous password invalid and forcing the switch on users. There should be a good login message when the users login to explain the requirement.

## WHY are we building?

To increase security on potentially compromised passwords or a mechanism to leverage when we rotate secrets.

## WHAT are we building?

Generally, we are adding a new mechanism to trigger and force a password reset among users, individually or in bulk. _Individually_ through a new password reset button on the user's page or in _bulk_ through API call or SQL script that would switch a database field for examples. The SQL script and database field option seems easier but this can be discussed.

1. An additional workflow for admin action for password reset that would be described as:
   1. Admin clicks a Password Reset button on the user's profile.
   2. The old password is confirmed to be obsolete and a new one will be required.
2. An additional workflow for password reset notification that would be described as:
   1. Following the admin reset trigger...
   2. A notification is sent to the user about the password reset containing an URL to the password reset page.
   3. The user clicks the URL and gets redirected to the existing password reset page that we already have in Notify.
3. An additional workflow for password reset through the login that would be described as:
   1. Following the admin reset trigger...
   2. A user trying to use their old password on the login page will get access denied. 
   3. the user gets a meaningful message about the error where we mention that a Notify admin required a password change and it might be to security concerns.
   4. The user gets redirected to the password reset page that we already have in Notify.

## VALUE created by our solution

More security while retaining a good user experience within Notify.

# Tasks

- [x] Add reset password button on the user profile.
- [x] Add database boolean field for expired password on the `users` table.
- [x] Add workflow logic to send email password reset notification to user(s).
- [x] Add workflow logic to catch users with expired password.
- [x] Map out the feature, backstage and frontstage & user flow @amazingphilippe and @adriannelee 
- [x] Design the screen(s) that come out of the mapping exercise @amazingphilippe 

# Acceptance Criteria** (Definition of done) 

- [x] Password reset can be triggered by a Notify admin on one user
- [x] Password reset can be triggered by a Notify admin on many users (potentially via a SQL script switching a database field on the `users` table).
- [x] Senders don't get stuck trying to log in.
- [x] Password reset disables the usage of the old password, forcing new password to be set.

# QA

- [x] Test the admin reset password button on the user page.
- [x] Test the password reset notification send once a user is requested to change his password.
- [x] Test the user cannot log in with old password once the password has been requested to change.
- [x] Test the user receives proper login message when he tried to login with old password.
- [x] Test the user can change his password successfully once the password has been change.
- [x] Test the user can login successfully with new password.

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/520?planning-poker) with ZenHub @amazingphilippe @adriannelee @sastels @iokpala @jzbahrai

**Comment by yaelberger-commits** [comment]
@amazingphilippe and @adriannelee we need to prioritize this work. I recognize that means a slight delay on tackling some a11y issues. Hope we can collaborate on this together over the next few days. I am available to help with content writing in EN and we can do a content critique with others at CDS to validate.

**Comment by adriannelee** [comment]
Mapping it out: https://miro.com/app/board/uXjVOAkOvNU=/?invite_link_id=39812574757

**Comment by yaelberger-commits** [comment]
Jimmy will test in Staging as a next step, Phil will review Design
