### ISSUE TITLE
Updating and Publishing our Service Level Objectives (SLO)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#548]
# Description

As a user of Notify,
I need to know what the SLOs of the service are,
So that I can level my expectations
and hit the system within defined constraints.

[Notes on SLO draft Sept. 7 ](https://docs.google.com/document/d/1WhurXvvh1qTYMJSd9L4UkcD62SUHWQmcTmwYLUnWLK0/edit?usp=sharing)

## WHY are we building?

To tell users what are the constraints of Notify system, to level expectations but also to prevent users from overflowing our service, hence stability and trust.
Support tickets suggest our clients think there are problems when sends take time. When sending delays are normal. 

## WHAT are we building?

Review current baseline values and update [our SLO document] and publish it for clients (https://docs.google.com/spreadsheets/d/1cJjCzqC9JOAq005jWg9OjmeYoQvLkPaAFkCaIZTcaWA/edit#gid=0).

## VALUE created by our solution

Trust and reliability.
If we update our SLOs to align with reality we can update our alarms and alerts in #notification-ops and get rid of some noise
Build trust and confidence with clients by being open and transparent with our performance indicators 
Self serve support for clients. They can figure out if Notify is performant enough for their use.

# Tasks
Design:
- [x] Ask Josh and Policy: Should SLOs be hard or soft commitments? Targets
- [x] Bring this to policy meeting to know what is our commitment and liability
- [x] [User journey map](https://miro.com/app/board/uXjVO6TPyIs=/) identifies where people would be coming from
- [x] Figure out where SLO fits in the IA (Also in relation SLA)
- [x] Design new SLO page in EN (includes the hard limits that we have to work with)
- [x] Subject matter expert review (the dev team and Adrianne) to check that the plain language revisions accurately represent the technical terminology.
- [x] Get content translated
- [x] Reviewed by @amazingphilippe 
- [x] Publish new SLOs

Dev:
- [x] Identify the hard limits to our goals
- [x] Review SLO dashboard in AWS, our SLOs for Notify and our actual objectives after baselining 
- [x] Make adjustments as needed
- [x] Update alerts based on new SLOs
- [x] Update and timestamp SLOs. Quarterly? Annually?

https://docs.google.com/spreadsheets/d/1fU-FJ7THfWEqNhbpQ4r22MQipFwC7SP851ZQnOf68cM/edit#gid=0

# Acceptance Criteria

As the Notify PM, given that more new clients will be onboarding to Notify and creating new services or asking for limit increases to their existing services, when we measure our performance against our SLOs, then we are able to meet them 100% of the time. 

As a Notify client, given that I need to have confidence and trust in using Notify as a reliable tool to send notifications, when I see the SLOs on the Notify website, then I am satisfied that Notify can handle the throughput and send all messages its receiving and will not go down or break unexpectedly. 

- [x] SLOs can be measured on a regular, quarterly basis with instructions
- [x] SLOs are achievable given current infrastructure and resources
- [x] Designs for SLO pages in EN and FR are ready for Design/Dev review

## QA Steps

- [x] Reviewed and sign off by Josh and Yael

**Comment by YedidaZalik** [comment]
Started work on plain language wording of [SLOs in this document](https://docs.google.com/spreadsheets/d/1lHSM3_ajYvcmY_SAR7MFjoMtVsH4YOw-fzIvlcqICEg/edit#gid=0)

**Comment by amazingphilippe** [comment]
We'll wait for a discussion with dev.
Still working on the language.

**Comment by YedidaZalik** [comment]
Initial work on plain language in [Plain lang SLO spreadsheet](https://docs.google.com/spreadsheets/d/1lHSM3_ajYvcmY_SAR7MFjoMtVsH4YOw-fzIvlcqICEg/edit?pli=1#gid=1989372846)

**Comment by YedidaZalik** [comment]
Design sync with Adrianne, Phil and Yedida to discuss where SLO's fit in Notify's IA.  We are thinking to create a separate page for SLO's in the footer. The page will be parallel to the Activity page, and will also link to it. The title of the page has not been finalized yet, but we are discussing including the words "Service level objectives" as well as "Performance metrics".
Rationale:
- Terminology "Service level objectives" will be expected by part of our audience, but may not be familiar to another part of our audience.
- We initially discussed combining Activity and SLO's into one page, but we realized these are very different. Activity is of interest to the CDS audience who are interested in how many services use Notify and how many messages are sent. But SLO details are different: these help users decide if Notify can meet their needs.
- We discussed possibility of a different information architecture that might include a landing page similar to the Guidance page. The Guidance page links to more detailed pages, and we could have a metrics page that links to more detailed metrics. However, as the purpose of this card is to make our SLO's transparent asap, we need to be able to add this content using GC Articles, which is possible if we just add a discrete page.  We would not be able to do that if we make more significant changes to the IA.

**Comment by YedidaZalik** [comment]
We'll resume once we have dev input. When we're ready here is our 
- [journey mapping to date](https://miro.com/app/board/uXjVO6TPyIs=/)
- tentative content in [yellow block](https://docs.google.com/spreadsheets/d/1lHSM3_ajYvcmY_SAR7MFjoMtVsH4YOw-fzIvlcqICEg/edit?pli=1#gid=58374374)

**Comment by YedidaZalik** [comment]
After mtg with one of the services, in consultation with @yaelberger-commits we'll also include the following content:
- Services can see their daily and annual limits in their service settings. Letting users know that if they try to send above their daily limit they will see failed messages is very good info to include.
- How long we keep our records of delivery
- Hard limits. We don't have the ability for users to pay to send above those limits. So let's just be upfront about that. 25,000 SMS and 10 M emails are the hard annual limits for each service.

**Comment by yaelberger-commits** [comment]
Meeting on Thursday with Jumana for dev sync

**Comment by YedidaZalik** [comment]
Attaching notes from [Sept 7 meeting](https://docs.google.com/document/d/1WhurXvvh1qTYMJSd9L4UkcD62SUHWQmcTmwYLUnWLK0/edit#heading=h.t590zkk6ho4l)

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/548?planning-poker) with Zenhub @jimleroyer @YedidaZalik @sastels

**Comment by yaelberger-commits** [comment]
Jimmy and Steve confirmed values and refined some baselining numbers. Can hand off to Yedida next.

**Comment by YedidaZalik** [comment]
@YedidaZalik to create contact to link SLOs to other pages.

**Comment by YedidaZalik** [comment]
Translation will send next week

**Comment by YedidaZalik** [comment]
Translation sent back [FR SLO's](https://docs.google.com/document/d/1vThtPYbEHUlb368OHvdv1Wkqmkskq8OQMf0aA2E8oOs/edit)
Ready for review by @amazingphilippe

**Comment by YedidaZalik** [comment]
@amazingphilippe to review

**Comment by amazingphilippe** [comment]
Reviewed and made a few edits to the French translation 

@YedidaZalik : I also formatted using some bullet points. Let me know if they make sense!

**Comment by YedidaZalik** [comment]
@amazingphilippe it looks good to me!

**Comment by YedidaZalik** [comment]
Phil made a few edits to link text
@YedidaZalik to post to GC articles after work on SLA

**Comment by adriannelee** [comment]
Yedida will put the draft up today.

**Comment by adriannelee** [comment]
Draft is on GC Articles. Waiting for review from @amazingphilippe

**Comment by adriannelee** [comment]
On GC Articles now. Will publish today. Need to add links on the Features page and in the footer.

**Comment by andrewleith** [comment]
SLO and SLA were both published last week!
Parts of other pages (home page, features, etc.) are still being updated this week by @amazingphilippe.
@amazingphilippe stuck on an AWS problem

**Comment by andrewleith** [comment]
@yaelberger-commits to QA

**Comment by andrewleith** [comment]
@yaelberger-commits to QA today.

**Comment by yaelberger-commits** [comment]
@jimleroyer what about updating our alerts to align to the new SLOs? Can we pull this back into the Product Backlog to finish that work?

**Comment by andrewleith** [comment]
Dates have been updated. Still waiting on alerts.

**Comment by jimleroyer** [comment]
The PR for the alerts:
https://github.com/cds-snc/notification-terraform/pull/696

**Comment by yaelberger-commits** [comment]
Has now been merged, moving to Done
