### ISSUE TITLE
Too many attachments causes failures

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#550]
# Describe the bug 

Too many attachments in an email (20 attachments) causes failures because it takes too much memory and causes a celery error.

https://notification.canada.ca/services/2ae2449a-a257-4591-beb5-0eea5d2f2ff1

# [Bug Severity]

SEV-3 Only impacting this one service and our team (time to investigate)

(https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

# To Reproduce

1. Create a template that attaches 20 files (each roughly ~300kb in size) using the [`attach` method](https://documentation.notification.canada.ca/en/send.html#sending-a-file-by-email).
2. Attempt to send a notification with the template.
3. Monitor the celery pods.  You will see a `SIGKILL` celery process termination.

# Expected behavior

Either of the following would be acceptable:

1. The notification sends successfully with all attachments; or
2. The user receives a validation error letting the user know that they have exceeded the allowed limit of file attachments.

# Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:
* User is unable to send a notification with too many attachment.

Impact on Recipients:
* Recipient does not receive the notification.

Impact on Notify team: 
* Ops channel is flooded with celery errors.

# Tasks

- [ ] Potentially increase the kubernetes pods' memory to allow for more file attachments.
- [ ] Stress test file attachments in a scenario with varying number and see what's the threshold for these.
- [ ] Discuss in the team what is the arbitrary limit we want to allow for file attachments. What is the acceptable limit? Consider provider's limit in the discussion.

# Acceptance criteria

- [ ] We have a performance profile on how much file attachments in sizes and numbers we can take.
- [ ] We have a validation limit on number of file attachments allowed in a notification.
- [ ] There is no more failures with too many attachments in a notification, especially with pods crashing.

# Additional context

* [Incident channel](https://gcdigital.slack.com/archives/C03ATFM506M) discussing the troubleshooting and fixes.
