### ISSUE TITLE
Notifications with numerous direct file attachments are not sent

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#592]
# Describe the bug 

Too many attachments in a notification can kill a celery worker and delay the sending of the notification by 4-5 hours.

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV2

This affects at least 2 users trying out Notify and I have the impression it will affect their way of working with it. The communication aspect with the users should be done faster (SEV2) but implementation might be lower priority depending on agreement with users.

# To Reproduce

1. Using the API, send a notification with 20 direct file attachments using [attach method](https://documentation.notification.canada.ca/en/send.html#sending-a-file-by-email).
1. Observe the notification causing the celery worker to terminate through the celery logs.

# Expected behavior

Actually, this one is tricky. Sending that many file attachments might not fit the normal quality notification that we expect. It's up to a discussion on what will be a proper balance on number of direct attachments to an email (if 20 is fine, what about 50? or 100?).

We should be able to handle 10mb file size.

We should definitely have a clear guideline on maximum number of attachments, validate it on template creation and notification send.

The workaround for users who want to send more attachments than the ones allowed for direct mode would be instead to use link mode instead, e.g. files directly attached to an email vs files linked into the email. The latter use less resource and will not case stability issues on the celery workers.

### Either of the following would be acceptable:

- The notification sends successfully with all attachments; or
- The user receives a validation error letting the user know that they have exceeded the allowed limit of file attachments.

# Impact

Notifications that define numerous direct file attachments are not getting sent. Users might have expectations of Notify as a file sending service, but this is not how Notify was built. Need to reconcile. 

## Impact on Notify users:

Unexpected behavior, loss of trust as Notify don't even prevent the sending of these notifications with too many direct file attachments.

## Impact on Recipients:

Notifications are not received.

## Impact on Notify team:

More issues and support tickets to deal with.

# Tasks

- [ ] Potentially increase the kubernetes pods' memory to allow for more file attachments.
- [ ] Stress test file attachments in a scenario with varying number and see what's the threshold for these.
- [ ] Discuss in the team what is the arbitrary limit we want to allow for file attachments. What is the acceptable limit? Consider provider's limit in the discussion.

# Acceptance criteria

- [ ] We have a performance profile on how much file attachments in sizes and numbers we can take. (Tests to verify different scenarios ex. 1 attachment at 10mb, 2 attachments at 5mb?) Or throw random # and size and see what fails
- [x] We have a validation limit on number of file attachments allowed in a notification.
- [x] Update API documentation with updated limits of size and #
- [x] There is no more failures with too many attachments in a notification, especially with pods crashing.

# Additional context
* [Incident channel](https://gcdigital.slack.com/archives/C03ATFM506M) discussing the troubleshooting and fixes.
* Related to #591 
* Related to #201

## Known failures reported by users
* https://cds-snc.freshdesk.com/a/tickets/9122
  * 7 x 375KB .PDF files (total size around ~ 3mb)
* https://cds-snc.freshdesk.com/a/tickets/8221
  * no details given on number or size of attachments
* https://cds-snc.freshdesk.com/a/tickets/8209 
  * ticket is tagged as an attachment bug, but no details re: attachments are given
* https://cds-snc.freshdesk.com/a/tickets/8004  
  * ticket is tagged as an attachment bug, but no details re: attachments are given

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/592?planning-poker) with ZenHub @patheard @sastels

**Comment by jimleroyer** [comment]
This card is a follow up from the analysis performed by #591. Recommendations out of it are to:

> I would suggest we focus on this in #592 and set attachment limits:
> 
> total number; and/or
> total size
> We'd need to do some testing to figure out where the "safe" number is that we want to support.

**Comment by jimleroyer** [comment]
@yaelberger-commits This affects more users now, this notification could not be sent (and seems sensitive and important):
https://notification.canada.ca/services/ac19b40d-176f-40dd-98ba-1715380c3d77/notification/31e70871-1d32-421a-b09a-6ca729de9d85

**Comment by jimleroyer** [comment]
Potential duplicate of #550

**Comment by yaelberger-commits** [comment]
Could include adding a validation rule for file attachments in UI. 
Do some research or performance tests to see where is the threshold for attachments crashing our K8n pods

**Comment by andrewleith** [comment]
Updated with tickets relating to known file attachment issues.

**Comment by jimleroyer** [comment]
Related PR that puts a constraint on number of attachments to 10:
https://github.com/cds-snc/notification-api/pull/1561

**Comment by yaelberger-commits** [comment]
Was duplicate of #550 and was fixed! Closing

**Comment by jimleroyer** [comment]
We might have seen a repetition of this issue with this freshdesk ticket:

* https://cds-snc.freshdesk.com/a/tickets/14776
