### ISSUE TITLE
Delete my service/account

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#636]
_Delete my service/account_

## Description

As a (user), I need to be able to do delete my account so that I no longer have access to a service or receive emails from Notify if I move off a team, change roles, or need to retire a service. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by foudamo** [comment]
Support ticket raised, Jimmy P asking for process  
Full slack thread https://gcdigital.slack.com/archives/CR9E3U95F/p1695738912643399 

Problem: Deleting API keys are self serve (process is clear). Service & Accounts are manual (process is unclear)

- What would be the process to delete service, & accounts?

Suggestions:

- Drafted response (thanks Jimmy P). **Any issues with it?**

> Hello,
> You are being contacted because you are administrative team members for the GC Notify service named “Log Anomaly Detector”.
> We have received a request to delete the service, and wanted to let you know of that request. Unless we hear back from you, we will proceed with the deletion of the service listed above. This will not affect your individual access to GC Notify.
> Thank you,
> The GC Notify Team

- **A timeline for when you will proceed with deleting the service?**
(suggestion from Mohamed, final decision up to PM) the industry standard is 30-90 days (Google does 30, Microsoft does 60, Facebook does 90). Unless this creates an issue to Helpdesk, I suggest the latter.

- **Who should this email go to?**
(suggestion from Mohamed, final decision up to PM) this email is a reply to a request. So it should be replied back to the sender + a heads up to all accounts associated to that service(s) and organization

- **Should we let folks know that the deletion is irreversible, in case they need to save any information or templates from Notify before their service is deleted?**
(suggestion from Mohamed, final decision up to PM) yes definitely

**Comment by foudamo** [comment]
Update notes from @adriannelee and @andrewleith 

Users (with admin rights, not to be confused with Notify-admins): 

- Can delete service
- Can give others rights to manage Settings & Team (when inviting others)
- Cannot delete user accounts (require contacting Notify support to "archive" account)

Users (without admin rights): 

- Cannot delete service
- Cannot delete user accounts (require contacting Notify support to "archive" account)


**What happens when a user is archived?**
All permissions for services for user are removed
Organization is unset for user
Email address is modified to an “archived” (actual email address is still kept in this string)
Password is overridden with a randomly generated guid
User state is set to inactive

**What happens when a service is archived?**
All templates created in the service are archived
All API Keys created in the service are revoked
Service state is set to inactive
Nothing happens to any user data of a service when it is archived

**Comment by yaelberger-commits** [comment]
Deleting a service is more complex because we want to be hands off, but there needs to be a check and balance to ensure a service is not deleted when it shouldn't be. Who on the team should be able to make this decision? How do we manage their permissions? What if other team members disagree? 

Because of the complexity of "Delete a Service" we could start our work with "Delete my Account" instead

**Comment by yaelberger-commits** [comment]
Relevant thread from GC Forms on deactivating users https://gcdigital.slack.com/archives/C01GFD150MC/p1708698162772819

**Comment by schancase** [comment]
closing this as planned -  all child items are now done!
