### ISSUE TITLE
Support clients sending up to 500,000?  emails a day

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#655]
_Support clients sending up to 500,000? emails a day_

## Description

As a user of Notify, I need to be able to send up to 500,000. 

WHY are we building?
We need to be able to scale up to meet the needs services that want to increase their usage of Notify for large volume jobs.

WHAT are we building?
???
https://miro.com/app/board/uXjVO3K9r9E=/

VALUE created by our solution
Other clients will be able to benefit from our increased capacity and we will be able to raise daily limits for more services upon request.

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] An incremental plan for increasing a client's daily limit

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario
