### ISSUE TITLE
Review tests that include static content

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#675]
Some tests call pages with static content that are now hosted on GCA.  For these tests, the call out to GCA should be mocked so there is no network request happening during the unit tests.

## TODO
- [x] Review all tests that call out to any route in `app/articles/routing.py/GC_ARTICLES_ROUTES`
- [x] better idea: use wireshark to monitor traffic while running tests to isolate which ones call out to GCA
- [x] Mock `get_page_by_slug` and `get_nav_items` to avoid the network call to GCA

## QA
- [ ] Ensure test suites pass on the scheduled runs for at least 24 hours

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/675?planning-poker) with ZenHub @andrewleith @jzbahrai @sastels

**Comment by yaelberger-commits** [comment]
Having an impact on entire release pipeline, less reliable tests. More alarms, more false lags

**Comment by andrewleith** [comment]
Using wireshark while running tests; these are the tests that call out to GCA:
- [ ] `test_errorhandlers.py/test_bad_url_returns_page_not_found`
- [ ] `test_utils.py/test_set_lang`
- [ ] `test_headers.py/test_presence_of_security_headers`
- [ ] `test_headers.py/test_headers_non_ascii_characters_are_replaced`
- [ ] `test_index.py/test_home_page_a11y`
- [ ] `test_index.py/test_query_params`
- [ ] `test_index.py/test_terms_page_has_correct_content` - this test cannot be run without calling GCA
- [ ] `test_index.py/test_static_pages_gca`

**Comment by yaelberger-commits** [comment]
Hourly tests haven't failed

**Comment by andrewleith** [comment]
Tests are no longer failing, all calls out to GCA have been removed.
