### ISSUE TITLE
Controlling our bounce rate

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#732]
_Controlling our bounce rate_

## Description

As a Notify Admin, I need to be able to suspend a service when they hit a 10% bounce rate so that I can prevent any single service from risking our reputation with AWS and having our service shut down. 

As a Notify client, I need to know what my bounce rate is, and what the consequence are of going over the threshold so I can prevent having my service suspended and continue using Notify to send notifications.

Calculate bounce rates for live services sending messages at a given time
Automatically suspend a service currently sending if their bounce rate goes above 10%

- Thresholds we need to decide
- Start tracking bounce rate
- Surface bounce rate to users in the dashboard
- implementing the emergency break
- Ideally we want to replicate the timeframe AWS uses, we could ask them what timeframe they use
- Ensure alarms match the thresholds we set

WHY are we building?
Would give us some reassurance to allow higher volumes and have risk mitigation for poor data collection.
Bounce rate wouldn't be so fragile because we would have higher volume

WHAT are we building?
Replicate AWS breaks on our system, automated breaks, not manual
- [x] ADR (define what a bounce rate is for email), set the threshold, etc.
- [x] Observability of what our overall bounce rate has been, but also per service 
- [x] Surface bounce rate in the dashboard for each service (currently only failure rate)
~~- [ ] Build and implement the emergency break (release 2.0)~~
- [x] Add details about bounce rate and responsibilities into existing policy docs for clients

VALUE created by our solution
We could open up the opportunity for clients to send higher volumes to meet the needs of some departments, while not introducing a large risk to our overall reliability of the service.

## Acceptance Criteria** (Definition of done) 

Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [x] send a warning alert to us when they reach 5% of bounce rate
~~- [ ] automatically suspend a service when they reach the threshold~~

## QA Steps

- [x] Tested in a realistic production scenario

## Notes

- The more traffic and volume we have with good data, the bigger bounce rate we can absorb
- We need to consider low volume use cases as well (100 notifications, 20 fail, 20% bounce rate)
- If we lower the threshold, we need to socialize that because it has been 10% since we launched
- Have to be consistent and it has to be something they can see on their dashboard. Has to be consistent from one day to the next. Has to be transparent and consistent and fair across services 
- First iteration, go with a simple solution, consider more sophisticated iteration in the future, like making use of scheduling

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/732?planning-poker) with ZenHub @andrewleith @jimleroyer @jzbahrai @patheard @sastels

**Comment by yaelberger-commits** [comment]
For UI, could use review apps to demo feature 
For backend changes, we don't have review apps. 
Use Feature flags? But then we have to clean up later.

**Comment by yaelberger-commits** [comment]
Spread over 2 sprints 
1) cover backend work for emergency break, but don't apply it yet. Send emails to the team first to let us know this would be a suspension, but not actually suspending
2) Focus on UI, once up and ready we implement emergency break for real

**Comment by yaelberger-commits** [comment]
Spread over 2 sprints 
1) cover backend work for emergency break, but don't apply it yet. Send emails to the team first to let us know this would be a suspension, but not actually suspending
2) Focus on UI, once up and ready we implement emergency break for real
