### ISSUE TITLE
Raise annual SMS volume from 25K to 100K

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#781]
Some users want to use Notify to send larger volumes of SMS per year than Notify currently allows because we have been limited by not having cost recovery, accounting and billing in place. 

We would like to be able to offer up to 100K free SMS a year to services that need that volume to meet their operational needs.

- [x] our team knows how many real texts we send a day 
- [ ] weekly report and PM monitoring and notifying services that they hit their limit and how close or over their limits our services are
- [x] have a rough picture of the priority of the text templates we send in a day (majority bulk or priority etc?)
- [x] update code to reflect the change
- [x] update content in GC Articles in 2 places to reflect the change
- [x] update support documents and processes to align with new limits

**Future work:**
- 1,200 SMS/minute in testing 400 SMS/minute in prod
- current limit of 20 SMS/sec with our AWS pool of longcodes
- Currently at around 7 SMS requests per second
- If we had our own pool of 100 longcodes, could send 100 SMS/sec
- rework SMS pipeline (scale celery workers etc.)

- users know how many real texts they are sending every day and how close to their annual limits they are

Users should be able to send a reasonable number of free SMS a year to meet their operational needs while not increasing the administrative and policy burden on either the Notify team or our users.

- [x]  there is executive support to move ahead with the limit increase
- [x]  content is updated to reflect the new limits - pages listed in [Notify references to fiscal year](https://docs.google.com/document/d/1W8an5zWmEKm5ssjPvKjfZuQbSroNUTznalech_oheIE/edit#heading=h.fih3v0ot99xd)
- [x]  support is made aware of the change

User insights from Freshdesk tickets
https://cds-snc.freshdesk.com/a/tickets/9432
https://cds-snc.freshdesk.com/a/tickets/9430

Leads deck https://docs.google.com/presentation/d/1gkl1qobrCZ0kCWPnLcq00NgrEl7dSJAsLG6HPMusjts/edit#slide=id.p

**Comment by yaelberger-commits** [comment]
it looks like our free sms limits are actually 100K right now
all services are type "central" which have a 100K limit

**Comment by yaelberger-commits** [comment]
Somehow this service has 250,000 free SMS limit in their settings. Not sure how?
https://notification.canada.ca/services/e31c03b2-450d-45f6-8a5d-ec2f3036154e/service-settings

**Comment by yaelberger-commits** [comment]
From @sastels 

Tangentially related: should we have different daily limits for SMS vs emails? It would be good to know about (and have to approve) large sms sends
IMO it's about the bursts - 100K spread over the year is about one ever 5 minutes. We can handle that. 100K all at once, that could be a problem.

**Comment by yaelberger-commits** [comment]
Out of scope for 2023/24 fiscal
