### ISSUE TITLE
Priority Queues 

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#807]
_Priority Queues _

## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by YedidaZalik** [comment]
This [NNM article ](https://www.nngroup.com/articles/virtual-queue-best-practices/?mc_cid=fff9c1b5f2&mc_eid=e7d6e47036)may be helpful

**Comment by yaelberger-commits** [comment]
@YedidaZalik I'm not sure it's relevant to our product, as our queues are not the same as a virtual line-up to access a busy website or order tickets, for example. Our queues are in our backend infrastructure, and they impact delivery of notifications, but it doesn't slow down the Senders from completing their tasks, but it does slow down the recipient from receiving the notifications in some cases. That's why we opted to leave these invisible to Senders, and instead explain our SLOs to Senders to better set expectations.
