### ISSUE TITLE
Users can create and edit formatted content in templates easily without issues

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#808]
_Users can create and edit formatted content in templates easily without issues_

## Description

As a Notify client, I need to be able to create, format and edit templates easily and successfully without errors or bugs in a self-serve manner so that I can send notifications with confidence that they will look the way I expect them to. 

We have identified a number of bugs and user needs from support tickets and our own testing. 

##Hypothesis 

- 

## Acceptance Criteria** (Definition of done) 

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

From @EliseKa FAQ work
-[ ] more info on [what formatting is available in GC Notify as well as what is not available ](https://docs.google.com/document/d/1wsqul4D6k8tuY4O4HxByH4T0rV060hBUaipd5x2m8pw/edit#heading=h.iyert861x788)

* A11y
* Bilingualism
* Measuring success and metrics

**Comment by schancase** [comment]
Refinement required to decide what we will target closing for Q4 vs Next FY. Create new Epic to parent work for next FY

**Comment by schancase** [comment]
Carolyn and I are removing this from the RTE-related KR as it is not related to RTE. This piece of work will be re-considered for future prioritization.
