### ISSUE TITLE
Complete 3rd party a11y audit

### ISSUE THREAD

**Issue by stephenyates-cds** [cds-snc/notification-planning#83]
As a user of Notify, I need the Notify UI and experience to be fully accessible, as well as the messages that I send, so that I can ensure I'm able to use the service and meet user needs for recipients. 

As the Notify team, we need to ensure that Notify meets all GC standards and web standards so that we can give our users confidence in choosing and adopting GC Notify as a solution for sending messages. 

Acceptance Criteria: 

Audit report: https://docs.google.com/document/d/1-4d3hIMz9VLXo6jCNIBJ4q43_jbcvQG8/edit

Airtable: https://airtable.com/shrWJbNBghJUS6xW3/tblfaz4gpuTt2HLYm

- [x] Work through Sabine to go through OCADUCO contract
- [x] Complete work before March 31 (End of Fiscal)
- [x] Does not include the public-facing website or messages themselves, limited in scope to the UI of the Notify service 
- [x] Task Authorization being developed by Sabine 
- [x] Move list of issues to Zenhub board as prioritized cards linked to an epic
- [x] Prepare deck to present audit results and prioritization to the team and stakeholders

**Comment by amazingphilippe** [comment]
Meeting with Shawn T:
- Discuss the issues with Shawn.
- Once issues are fixed, Shawn will do an audit on GC Notify.
- Shawn will open up new issues for accessibility concerns found.
- Shawn will work with team on suggestions in dealing with future accessibility concerns.
- CDS will document the steps taken and produce a blog / post.

**Comment by amazingphilippe** [comment]
Setting up IDRC with testing credentials

**Comment by yaelberger-commits** [comment]
Giving testing credentials to Justin for the audit
Can we use one of our own email address + something else. 
Possibly Yael's email.

**Comment by adriannelee** [comment]
Tasks for auditing: https://docs.google.com/document/d/1e45C2y_RuyelrAztyktdlF5k5ZPM_aZmDFMN-RF23aE/edit

**Comment by yaelberger-commits** [comment]
We will move to Done once all the issues identified in the audit have been added as cards on the board.

**Comment by yaelberger-commits** [comment]
Need to move the remainder of issues to Zenhub backlog to Notify-planning repo so everything is in one place

**Comment by yaelberger-commits** [comment]
Keep in Product backlog until we run out of a11y issues to work on, then we can bring back into progress to bring in more issues from Airtable via automation
