### ISSUE TITLE
Increase the security, reliability and usability of Notify to fix critical issues.

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#852]
## Key Results
- [ ] We fix 80% of the critical a11y compliance requirements identified in the A11y Airtable. We disclose any critical a11y issues we are unable to fix in our Accessibility Statement 

- [ ] We fix 80% of the critical bilingual issues or inequalities identified in the backlog. We have a process in place to audit, find and fix untranslated content in the product, both on public pages and authenticated pages.

- [x] We have resolved 100% of the critical usability issues in the Product Backlog and validated the fixes with a round of usability testing.

- [ ] Meet all timelines for patching vulnerabilities at various severity levels for SNYK issues according to [CDS patch management policies](https://github.com/cds-snc/platform-core-services/wiki/Patch-management#patching-timelines). 

- [ ] Address 100% of known high priority security issues and 80% of medium priority in [Airtable](https://airtable.com/appABo5w7s1QNwcPP/tbly7xWWiYbftS8u8/viwg0s3dA8xbBpXwg?blocks=hide).

**Comment by connorscarolyns** [comment]
Epic no longer needed
