### ISSUE TITLE
Complete all jobs while maintaining SLOs as demand increases.

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#872]
## Key Results
- [ ] Free SMS limit is raised from 25,000 to 100,000 for all services with no related downtime or lost messages and 5 services send 50,000 SMS a day while we continue to meet our SLOs.

- [ ] Our throughput is increased so that Notify can reach 90% of the rate limits for emails and SMS per second set by AWS with no alarms or dropped notifications.

- [ ] Notify can handle 3 live services sending 500,000 daily at the same time batch volume for the bulk priority lane successfully while meeting our SLOs. 

- [ ] The burst size of notifications over the past 12 months is understood and Notify is able to send 1.5 times that volume while still meeting our SLOs.
