### ISSUE TITLE
Understand the needs of potential PTM clients and have a plan in place to update the service to address these needs

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#873]
## Key Results
- [x] We will have run a discovery.

- [x] We will have gathered insights into new use cases and volume/speed needs of potential new clients at the PTM levels.

- [x] We will have a plan (in the form of a roadmap, story map or backlog) to meet the size and shape of that demand. 

~~- [ ] We will start to modify Notify to meet those demands while piloting with 3 new P/T partners.~~

Folder for research activity work and artifacts https://drive.google.com/drive/folders/1nwqUqLJSoX2mSiyJC3HAIi0LTHiFMvPj
