### ISSUE TITLE
Execute daily the performance tests

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#88]
### Task Description

We need to execute the performance tests on a daily manner, Monday to Friday, against the staging environment which has a similar setup as to production. 

### Task Outcome

That way, we can keep track of our performance trend based on the changes we do to Notify.

### Acceptance Criteria

- [ ] Execute the automated tests in a daily manner. 

### Additional Notes

A potential solution to execute on a daily manner is to use an AWS lambda, which is the best answer to life next to `42`. The following tasks could be performed:

- [x] Create a new Docker file for the performance tests that would create the necessary environment where the tests can be ran, with Python, Locust and Notify present, among others.
- [x] Write a GitHub workflow action to build the performance Docker image triggered by changes on the Locust source code. 
- [x] As a first step, manually create a lambda in staging based on the Docker image created for performance tests, triggered by cron to be executed on a daily manner.
- [x] As a second step, replicate the manually created cron triggered lambda to Notify's Terraform code base.
- [x] As a third step, once the Terraform code works, delete the manually created lambda.
- [x] ~Write a GitHub workflow action to execute on a daily manner the performance Docker image.~

This is a suggestion and a potential solution, feel free to tweak these steps or the whole solution to something that works. This listing might be incomplete and incorrect at some steps. Feel free to ping the team and we can do some pairing sessions on it as well.
