### ISSUE TITLE
Email daily limit for all services MVP

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#887]
As a Notify Sender, I am confused about my daily limits and what they're for, so I need clarity and certainty about my email daily limits so that I can plan my sending accordingly, and know when I need to reach out to ask for an increase.

Why are we building
Because we introduced a daily SMS limit, our daily notification limit no longer really makes sense and would be less confusing if we also had a daily email limit.

Value we hope to create
Reducing confusion for Senders
Less cognitive load on Senders to have to think through daily limit actually being emails or have to send support ticket
Increase security by having appropriate daily limits to the volume someone can send if a service gets hacked

What we plan to build
Daily email limit (both in the backend) and also in the settings in the UI
emails and email content with warnings when close to the limit (80%) and when limit is reached
Error messages for API, and in the Admin
Mirror solution for SMS limits
Public website limits review (Add daily email limits to SLA)
Check API documentation

**Ensure new Terms of Use reflects new email daily limit as well as new SMS daily limit**

## Acceptance Criteria

Scope 
- get up to where SMS limit and then stop
- Improvements would be for future, out of scope for now

- [x] Review applicable findings and insights from SMS limits testing (settings page and email warning) and apply to this feature as well
- [x] Determine default daily email limit **10,000**
- [x] Honour legacy services with a higher daily limit
- [x] Feature flag to be able to turn this feature on or off
- [x] Global daily notification limit is retired
- [x] Move new email daily limit and SMS daily limit in settings under each respective heading
- [x] Database column is renamed to email limit from notification limit (not doing this as it blocks the DB)
- [x] Relocate the daily limit check from the celery to the API entry door like we did for our SMS parts work

**Notes from Story Refinement** https://docs.google.com/document/d/1DRnDodsCiaXHTeVlKVpWDeDtO5wOrp3gMGTTfS_yaIY/edit
## QA
- [x] Tested in Staging
- [x] You only get email emails when you reach the daily email limit or the 80% threshold, not the SMS email or the global email

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/887?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels @smcmurtry @amazingphilippe

**Comment by smcmurtry** [comment]
I'm estimating high since we will also need to update the 3 email templates related to this: "you've sent 80% of your limit", "you reached your limit", "your limit was changed"

**Comment by amazingphilippe** [comment]
We can update the template with a variable for notification type. Hopefully with minimal changes to those templates.

**Comment by sastels** [comment]
if we create a new "email_daily_limit" column we should be able to set the value from the general limit in the migration
https://stackoverflow.com/questions/24612395/how-do-i-execute-inserts-and-updates-in-an-alembic-upgrade-script/24623979#24623979

**Comment by yaelberger-commits** [comment]
Need to balance good UX with keeping Notify secure by keeping daily limits more honest. We should share the reason why we keep limits honest with users to help them understand why we do it this way.

**Comment by yaelberger-commits** [comment]
Warning emails if we are going to decrease their daily limit a week in advance
Auditing services on a more regular basis
Setting a time limit for large increases (6 months for example) before reducing the daily limit back down again

**Comment by yaelberger-commits** [comment]
After our refinement discussion we were leaning towards making daily email limit default 10,000 instead of 9,000 and just continuing to allow services to request increases as needed

**Comment by yaelberger-commits** [comment]
Limits and warnings
Error msgs
Mirror SMS solution
Include in dashboard
Replace daily notification limit with email limit in documentation (eg. TOU) and API documentation
Feature flag


Scope 
- get up to where SMS limit and then stop
- Improvements would be for future, out of scope for now
