### ISSUE TITLE
Routine: Update renovate dependencies

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#914]
# Description

As an ops lead,
I want Notify patched with its dependencies,
So that it is secure and running the latest.

As a GCNotify user,
I want Notify secure,
So that I can trust it.

# Acceptance Criteria** (Definition of done) 

Review and update renovate PRs on the following repositories:

### Tasks

- [notification-utils](https://github.com/cds-snc/notification-utils/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] minor deps
  - [x] chore branches
- [notification-admin](https://github.com/cds-snc/notification-admin/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] configure renovate: [example config](https://github.com/cds-snc/notification-api/blob/main/renovate.json) (tbd)
  - [x] minor deps 
  - [x] chore branches 
- [notification-api](https://github.com/cds-snc/notification-api/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] minor deps
  - [x] chore branches
- [notification-document-download-api](https://github.com/cds-snc/notification-document-download-api/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] minor deps 
  - [x] chore branches
- [notification-documentation](https://github.com/cds-snc/notification-documentation/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] configure renovate: [example config](https://github.com/cds-snc/notification-api/blob/main/renovate.json) 
- [notification-manifests](https://github.com/cds-snc/notification-manifests/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [ ] minor deps 
  - [ ] pin deps 
- [notification-pr-bot](https://github.com/cds-snc/notification-pr-bot/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [x] configure renovate: [example config](https://github.com/cds-snc/notification-api/blob/main/renovate.json) 
- [notification-terraform](https://github.com/cds-snc/notification-terraform/pulls?q=is%3Apr+is%3Aopen+renovate)
  - [ ] minor deps 
  - [ ] chore branches

# QA Steps

- [x] Local environment run fine locally (when appropriate)
- [x] Review environment run fine
- [x] Staging environment run fine

# Extended QA Steps when doing big changes

Performance tests
- [x] do some perf tests staging and compare with results from python tests

Smoke tests
- [x] run smoke tests on staging

Admin
  - [x] create new user / service / template
  - [x] send a few emails and sms
 
API
- [x] send an email notification
- [x] send an sms notification
- [x] send a bulk email notification
- [x] send a bulk sms notification

**Comment by YedidaZalik** [comment]
Andrew tagged Pat and Jimmy. May need to sync with Pat.

**Comment by yaelberger-commits** [comment]
@andrewleith is this a duplicate card of the epic "Integrate Renovate?" #878

**Comment by andrewleith** [comment]
@yaelberger-commits , I believe #878 is a one-time task to get renovate setup in each one of our repos.  This card is intended to be a per-sprint task to actually look through the renovate-generated PRs and action them in each repo.

**Comment by yaelberger-commits** [comment]
@andrewleith thank you for the clarification! That's clear

**Comment by adriannelee** [comment]
Andrew worked on this last week. @jimleroyer and @andrewleith will pair. Discovery will start tomorrow.

**Comment by sastels** [comment]
Note that we haven't added renovate to the pr-bot repo yet.

**Comment by andrewleith** [comment]
- made progress on `api`
- made progress on `utils` 
- still many PRs left

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/914?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @Pensai @sastels @smcmurtry

**Comment by andrewleith** [comment]
- Continuing on this this week;  utils and document-download just about finished; api ongoing

**Comment by andrewleith** [comment]
- utils and api done
- chore PRs left to do
- will wait for python 3.10 PRs to go first
- @smcmurtry will start on admin today

**Comment by jimleroyer** [comment]
Hit some issues with admin and Flask upgrade. Digged into GDS history and will try an incremental approach to upgrade to 2.1 and then 2.2.

**Comment by jimleroyer** [comment]
Meet offline to speak about how to define the task and what is considered done.

**Comment by jimleroyer** [comment]
Andrew to update the cards checkboxes. We will make a test session.

**Comment by andrewleith** [comment]
- Waiting for the last Python bump on API

**Comment by jimleroyer** [comment]
Andrew to merge latest Python changes for API to test these changes.

**Comment by jzbahrai** [comment]
@andrewleith going to look at it today.

**Comment by yaelberger-commits** [comment]
2 left to go after Python updates
Admin/API still need to be merged
Need approval on API PR

**Comment by yaelberger-commits** [comment]
Plan to get into staging after today's release, give them a good kick and release later in the week
