### ISSUE TITLE
SMS V1 Release

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#947]
### Tasks

- [x] Establish default limits for users, i.e. 1,000 by default for non SMS users and arbitrary value based on historic limit & usage for current SMS users.
- [x] Verify that legacy SMS services' current limits are honoured when we introduce new limits ([query]). **Note**: we need to decide how much over their max usage we will set their new limit to. 25% grace @sastels (https://docs.google.com/spreadsheets/d/1lVTAruwDJuobushcFUbJLQqtwFwimPe_3RVKCBz6NMY))
- [x] prep PR to turn on feature flag to put this into production @smcmurtry 
- [ ] ADR @smcmurtry @andrewleith @sastels, @jimleroyer will review

#### General:
- [x] New trial service gets limit 50 @yaelberger-commits 
- [x] Going live bumps up to 1000 @yaelberger-commits 
- [x] UI change on settings page @yaelberger-commits 
- [x] changing the sms daily limit triggers the correct email @sastels 
- [x] receive correct amount of emails based on limits and that the message content is correct (Should get only 1 close to limit and reached limit email but this resets when change limit) @sastels 
- [x] Designers to review EN and FN content for typos @YedidaZalik 

#### Sending
- /sms:
  - [x]  Cannot hop over the limit (with proper error message) @jzbahrai 
  - [x]  Can go up to the limit and next send is blocked (with proper error message) @jzbahrai 
- /bulk:  
  - [x] Cannot hop over the limit (with proper error message) @andrewleith 
  - [x] Can go up to the limit and next send is blocked (with proper error message) @andrewleith  
- Admin send to yourself: @Pensai 
  - [x] Cannot hop over the limit (with proper error message) 
  - [x] Can go up to the limit and next send is blocked (with proper error message)
- Admin send to one recipient: @Pensai 
  - [x] Cannot hop over the limit (with proper error message)
  - [x] Can go up to the limit and next send is blocked (with proper error message)
- Admin send to many: @jimleroyer 
  - [x] Cannot hop over the limit (with proper error message)
  - [x] Can go up to the limit and next send is blocked (with proper error message)
- Existing email sending functionality is unchanged - can send emails when over sms limit
  - [x] /email
  - [x] /bulk
  - [x] admin send to yourself
  - [x] admin send to one recipient
  - [x] admin send to many recipients

## After release

**Comment by adriannelee** [comment]
Blocked due to bugs

**Comment by adriannelee** [comment]
Done but adding a task for completing the ADR

**Comment by andrewleith** [comment]
ADR has been merged.
