### ISSUE TITLE
(Week 1-2) Stakeholder interview

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#966]
### Questions to answer

- Historically, what were the outcomes of a similar scenario where a federal product/service was used by another jurisdiction? What are the outcomes?
- What are advice CDS stakeholders have for us conducting this activity?
- Is it fair to prioritize federal clients once PTM clients are onboarded? If so, could we proactively disclose this?
- What are assumptions CDS stakeholders have about this Discovery activity?
- Even if we prioritize federal clients, are there PTM use cases that may have to be prioritized, for example, for public health reasons?
- What is our priority for serving clients? From a mandate, value, relationship perspective
- What do we mean by "prioritize"? Could our SLOs be different (lesser) for PTM clients?
- If we do not prioritize federal clients, could this impact their satisfaction with the service?
- Could we afford to cover the costs of more services and is there a cap or upper limit to how much we can spend monthly or annually to run Notify?

### Tasks

- [x] List of potential invitees - who would help answer these questions? **Yael**
- [x] Create invitation message **Yedida**
- [x] Make a copy and modify [privacy statement](https://docs.google.com/document/d/1Ic3k5eVwHOZ0P16t5AJ-sWF5aVL0M_sK3yclpL9j2xQ/edit) to suit this activity **Yedida**
- [x] Translate message **Yedida**
- [x] Translate privacy statement **Yedida**
- [x] Send out message **Yael**
- [x] Create facilitation guide **Yael**
- [x] Facilitate sessions **Yael, Yedida and Josh**
- [x] Analyze sessions **Yael Yedida Phil and Adrianne**

**Comment by yaelberger-commits** [comment]
10 invited to CDS stakeholders were sent out this morning. So far 3 have booked times

**Comment by yaelberger-commits** [comment]
All 10 interviews booked.

**Comment by yaelberger-commits** [comment]
Notes can be found in our PTM Discovery folder

**Comment by adriannelee** [comment]
3 interviews done, 4 today, 3 tomorrow

**Comment by andrewleith** [comment]
Interviews were completed last week and an session for analysis is planned for today.

**Comment by andrewleith** [comment]
Still doing analysis. Summary of findings to come soon.

**Comment by andrewleith** [comment]
- Continuing analysis today

**Comment by andrewleith** [comment]
- Final report is being worked on

**Comment by andrewleith** [comment]
- @adriannelee to review the "so-whats" and finalize
