### ISSUE TITLE
(Week 1-3) Interview with PTMs

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#968]
### Questions to answer

- Do PTMs need a solution like Notify?
- What are ways we will further our product mission if we onboard PTMs?
- What are ways we'll be distracted from our product mission if we onboard PTMs?
- What bodies could fall under  PTMs?  Could these include administrative tribunals at the provincial level?
- What factors contribute to PTMs wanting to fork their own Notify?
- What kind of language needs will PTM Recipients have from PTM Senders' perspectives?
- As is, what do PTMs find valuable about Notify?
- What does the configuration of PTM teams that would use Notify look like? Is there hierarchy?
- How important is branding/ customization to a PTM?
- In general, do PTMs have dev teams on staff that can integrate Notify programatically?
- What do PTM Senders need in order to create a trustworthy message?
- Do PTMs who want to use Notify require approvals? From whom?
- Would managing bodies block or unblock adoption of Notify? re: our mission for self-serve tools
- Does having no service owner/ managing body for PTs create barriers for PTM teams?
- What sort of formal documentation would be required for PTMs?
- Does PTMs make sure that their content (such as newsletter) has proper data collection policies along with un/subscription mechanism, in order to avoid recipients reporting these as spam?
- Are PTMs reluctant to use Notify due to inter-jurisdictional relationships?
- What are the use cases PTMs have in mind for Notify?

### Tasks
- [x] List of potential invitees - who would help answer these questions? **Adrianne**
- [x] Create invitation message **Adrianne**
- [x] Make a privacy statement **Adrianne**
- [x] Translate message **Adrianne**
- [x] Translate privacy statement **Adrianne**
- [x] Send out message **Adrianne**
- [x] Create facilitation guide **Adrianne**
- [x] Translate facilitation guide **Adrianne**
- [x] Facilitate sessions **Adrianne, Yael, Yedida, Phil, Jimmy**
- [x] Analyze sessions **Adrianne, Yael, Yedida, Phil**

**Comment by adriannelee** [comment]
I sent out the majority of messages yesterday. Waiting on a French Calendly link before sending out to QC folks.

**Comment by amazingphilippe** [comment]
[French Calendly link](https://calendly.com/philippecaron/entrevue-avec-gc-notification)

**Comment by adriannelee** [comment]
Yesterday - Prepped note takers, created note taking doc, did last minute checks before the sessions
Today - 6 sessions happening today between me and Yael

**Comment by andrewleith** [comment]
- Extending the sessions today and tomorrow to get more municipalities
- No luck getting anyone for French sessions for this week

**Comment by adriannelee** [comment]
We decided to write the final discovery report with a caveat that we don't know enough about French-speaking regions or bilingual regions. We'll do a more focused round of interviews with just French/multilingual regions

Had the group analysis session today, will have another one on Thursday morning in place of backlog refinement.
Folks can continue to tag the stickies till then : D !

**Comment by andrewleith** [comment]
- @adriannelee to continue analysis/sticky-tagging today

**Comment by andrewleith** [comment]
- did a lot last week as a group
- @adriannelee to continue with the "so-whats" and finalize the written parts
