### ISSUE TITLE
(Week 1-3) Interviews with civil society stakeholders (of PTMs)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#969]
### Questions to answer
* What are ways we will further our product mission if we onboard PTMs?
* What are ways we'll be distracted from our product mission if we onboard PTMs?
* What kind of language needs will PTM Recipients have from PTM Senders' perspectives?

[Folder](https://drive.google.com/drive/u/0/folders/1xm9_ywT37u4Yh8SViV9M915rMg7oAl9V)

### Tasks
- [ ] List of potential invitees - who would help answer these questions? **Adrianne & ?**
- [x] Create invitation message **Yedida**
- [x] Make a privacy statement **Yedida**
- [ ] Translate message ****
- [ ] Translate privacy statement ****
- [ ] Send out message ****
- [ ] Create facilitation guide ****
- [ ] Translate facilitation guide ****
- [ ] Facilitate sessions **Adrianne, Yael, Yedida**
- [ ] Analyze sessions **Adrianne, Yael, Yedida**

**Comment by adriannelee** [comment]
Started gathering potential invitees reading through stakeholder interviews

**Comment by YedidaZalik** [comment]
Integrated comments from Adrianne and Yael on recruitment email and privacy statement.
Sharly approved privacy statement.
Sent both docs to translation, requesting return on Tuesday.

**Comment by adriannelee** [comment]
We're going to re-evaluate how we approach this and who we approach

**Comment by YedidaZalik** [comment]
Translation of recruitment message and privacy statement have been returned. Attaching them here.
[Civil society recruitment message](https://docs.google.com/document/d/1uMFym3tFXZQIrjpUJgUhBqi589Bo3WJamoVguUrINno/edit)
[Civil society privacy statement](https://docs.google.com/document/d/13g7M9SfoTrEGius0dW1IrryNMOU-ntRkrZVS0VplZz4/edit#heading=h.gjdgxs)

**Comment by connorscarolyns** [comment]
closing as stale
